"Filed out from Dolphin Smalltalk"!

WAObject subclass: #JQAjaxAbstractInternalCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQAjaxAbstractInternalCallback guid: (GUID fromString: '{da590c89-bc2f-4f5d-af4b-1b81bca7e4f6}')!

JQAjaxAbstractInternalCallback comment: ''!

!JQAjaxAbstractInternalCallback categoriesForClass!JQuery-Core-Objects! !

!JQAjaxAbstractInternalCallback methodsFor!

process	self subclassResponsibility! !

!JQAjaxAbstractInternalCallback categoriesForMethods!
process!processing!public! !
!

