"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQBlackTieTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQBlackTieTheme guid: (GUID fromString: '{4fa1b0e0-115f-4bef-89a2-1d06caf4b4fd}')!
JQBlackTieTheme comment: ''!
!JQBlackTieTheme categoriesForClass!JQuery-UI-Libraries! !
!JQBlackTieTheme methodsFor!

themeName	^ 'black-tie'! !
!JQBlackTieTheme categoriesFor: #themeName!accessing!public! !

