"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQBlackTieTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQBlackTieTheme guid: (GUID fromString: '{69de6727-a4fd-4d67-9f9a-4e88a6f6fcb2}')!

JQBlackTieTheme comment: ''!

!JQBlackTieTheme categoriesForClass!JQuery-UI-Libraries! !

!JQBlackTieTheme methodsFor!

themeName	^ 'black-tie'! !

!JQBlackTieTheme categoriesForMethods!
themeName!accessing!public! !
!

