"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQBlitzerTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQBlitzerTheme guid: (GUID fromString: '{da396897-2715-4105-8519-ef73aa12dcd2}')!

JQBlitzerTheme comment: ''!

!JQBlitzerTheme categoriesForClass!Libraries! !

!JQBlitzerTheme methodsFor!

themeName	^ 'blitzer'! !

!JQBlitzerTheme categoriesForMethods!
themeName!accessing!public! !
!

