"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQBlitzerTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQBlitzerTheme guid: (GUID fromString: '{d83186ed-9a8c-49bf-b25e-f9be5f068914}')!
JQBlitzerTheme comment: ''!
!JQBlitzerTheme categoriesForClass!JQuery-UI-Libraries! !
!JQBlitzerTheme methodsFor!

themeName	^ 'blitzer'! !
!JQBlitzerTheme categoriesFor: #themeName!accessing!public! !

