"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQBlackTieTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQBlackTieTheme guid: (GUID fromString: '{6a8e2c39-754d-470c-b85f-7e103b99ad80}')!

JQBlackTieTheme comment: ''!

!JQBlackTieTheme categoriesForClass!Libraries! !

!JQBlackTieTheme methodsFor!

themeName	^ 'black-tie'! !

!JQBlackTieTheme categoriesForMethods!
themeName!accessing!public! !
!

