"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQBlitzerTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQBlitzerTheme guid: (GUID fromString: '{506b3125-1c51-43af-a952-79eeeaa02a4d}')!
JQBlitzerTheme comment: ''!
!JQBlitzerTheme categoriesForClass!JQuery-UI-Libraries! !
!JQBlitzerTheme methodsFor!

themeName	^ 'blitzer'! !
!JQBlitzerTheme categoriesFor: #themeName!accessing!public! !

