"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQCupertinoTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQCupertinoTheme guid: (GUID fromString: '{9381b37c-78c9-4dff-a04e-7482a2b3d789}')!

JQCupertinoTheme comment: ''!

!JQCupertinoTheme categoriesForClass!Libraries! !

!JQCupertinoTheme methodsFor!

themeName	^ 'cupertino'! !

!JQCupertinoTheme categoriesForMethods!
themeName!accessing!public! !
!

