"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQCupertinoTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQCupertinoTheme guid: (GUID fromString: '{7980dae7-c73b-427e-adaa-f0728a119111}')!
JQCupertinoTheme comment: ''!
!JQCupertinoTheme categoriesForClass!JQuery-UI-Libraries! !
!JQCupertinoTheme methodsFor!

themeName	^ 'cupertino'! !
!JQCupertinoTheme categoriesFor: #themeName!accessing!public! !

