"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQCupertinoTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQCupertinoTheme guid: (GUID fromString: '{74a3e036-bd50-4d21-8782-ea2b17d2d987}')!

JQCupertinoTheme comment: ''!

!JQCupertinoTheme categoriesForClass!JQuery-UI-Libraries! !

!JQCupertinoTheme methodsFor!

themeName	^ 'cupertino'! !

!JQCupertinoTheme categoriesForMethods!
themeName!accessing!public! !
!

