"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQDarkHiveTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQDarkHiveTheme guid: (GUID fromString: '{2ffea7c0-90fe-48a8-b2ec-b5bf38a1b620}')!
JQDarkHiveTheme comment: ''!
!JQDarkHiveTheme categoriesForClass!JQuery-UI-Libraries! !
!JQDarkHiveTheme methodsFor!

themeName	^ 'dark-hive'! !
!JQDarkHiveTheme categoriesFor: #themeName!accessing!public! !

