"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQDarkHiveTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQDarkHiveTheme guid: (GUID fromString: '{54f0dd7e-6e09-4a0a-a06a-3c18b1e5c717}')!

JQDarkHiveTheme comment: ''!

!JQDarkHiveTheme categoriesForClass!Libraries! !

!JQDarkHiveTheme methodsFor!

themeName	^ 'dark-hive'! !

!JQDarkHiveTheme categoriesForMethods!
themeName!accessing!public! !
!

