"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQDarkHiveTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQDarkHiveTheme guid: (GUID fromString: '{8b0aec50-cb0d-490a-a80b-bea07b0e3133}')!

JQDarkHiveTheme comment: ''!

!JQDarkHiveTheme categoriesForClass!JQuery-UI-Libraries! !

!JQDarkHiveTheme methodsFor!

themeName	^ 'dark-hive'! !

!JQDarkHiveTheme categoriesForMethods!
themeName!accessing!public! !
!

