"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQDotLuvTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQDotLuvTheme guid: (GUID fromString: '{a55a820d-778f-4b2f-8a6e-c65c0abf0811}')!

JQDotLuvTheme comment: ''!

!JQDotLuvTheme categoriesForClass!JQuery-UI-Libraries! !

!JQDotLuvTheme methodsFor!

themeName	^ 'dot-luv'! !

!JQDotLuvTheme categoriesForMethods!
themeName!accessing!public! !
!

