"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQDotLuvTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQDotLuvTheme guid: (GUID fromString: '{4c42dda2-1295-49c3-a24a-c68642b72415}')!

JQDotLuvTheme comment: ''!

!JQDotLuvTheme categoriesForClass!Libraries! !

!JQDotLuvTheme methodsFor!

themeName	^ 'dot-luv'! !

!JQDotLuvTheme categoriesForMethods!
themeName!accessing!public! !
!

