"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQDotLuvTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQDotLuvTheme guid: (GUID fromString: '{b9ca9f07-573f-4bc5-8c77-c4752d143e9c}')!
JQDotLuvTheme comment: ''!
!JQDotLuvTheme categoriesForClass!JQuery-UI-Libraries! !
!JQDotLuvTheme methodsFor!

themeName	^ 'dot-luv'! !
!JQDotLuvTheme categoriesFor: #themeName!accessing!public! !

