"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQEggplantTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQEggplantTheme guid: (GUID fromString: '{e6db8f7c-933f-4ae3-b5f8-197d1eb91d26}')!

JQEggplantTheme comment: ''!

!JQEggplantTheme categoriesForClass!JQuery-UI-Libraries! !

!JQEggplantTheme methodsFor!

themeName	^ 'eggplant'! !

!JQEggplantTheme categoriesForMethods!
themeName!accessing!public! !
!

