"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQEggplantTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQEggplantTheme guid: (GUID fromString: '{12d085c3-807c-48c2-81b3-d262c09f382a}')!
JQEggplantTheme comment: ''!
!JQEggplantTheme categoriesForClass!JQuery-UI-Libraries! !
!JQEggplantTheme methodsFor!

themeName	^ 'eggplant'! !
!JQEggplantTheme categoriesFor: #themeName!accessing!public! !

