"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQEggplantTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQEggplantTheme guid: (GUID fromString: '{aff51d15-f8be-45f2-958a-7e4d90bb8fc3}')!
JQEggplantTheme comment: ''!
!JQEggplantTheme categoriesForClass!JQuery-UI-Libraries! !
!JQEggplantTheme methodsFor!

themeName	^ 'eggplant'! !
!JQEggplantTheme categoriesFor: #themeName!accessing!public! !

