"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQExciteBikeTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQExciteBikeTheme guid: (GUID fromString: '{8098634e-cb31-4c50-9942-68fcdfebdac9}')!

JQExciteBikeTheme comment: ''!

!JQExciteBikeTheme categoriesForClass!Libraries! !

!JQExciteBikeTheme methodsFor!

themeName	^ 'excite-bike'! !

!JQExciteBikeTheme categoriesForMethods!
themeName!accessing!public! !
!

