"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQExciteBikeTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQExciteBikeTheme guid: (GUID fromString: '{f8682fc3-4fcd-494b-bee4-c47cb3385f69}')!
JQExciteBikeTheme comment: ''!
!JQExciteBikeTheme categoriesForClass!JQuery-UI-Libraries! !
!JQExciteBikeTheme methodsFor!

themeName	^ 'excite-bike'! !
!JQExciteBikeTheme categoriesFor: #themeName!accessing!public! !

