"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQExciteBikeTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQExciteBikeTheme guid: (GUID fromString: '{0b2b9139-4dff-4e06-8bf3-0692f595815c}')!

JQExciteBikeTheme comment: ''!

!JQExciteBikeTheme categoriesForClass!JQuery-UI-Libraries! !

!JQExciteBikeTheme methodsFor!

themeName	^ 'excite-bike'! !

!JQExciteBikeTheme categoriesForMethods!
themeName!accessing!public! !
!

