"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQFlickTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQFlickTheme guid: (GUID fromString: '{7735f317-ebed-4e60-bf67-af00a7e92952}')!

JQFlickTheme comment: ''!

!JQFlickTheme categoriesForClass!Libraries! !

!JQFlickTheme methodsFor!

themeName	^ 'flick'! !

!JQFlickTheme categoriesForMethods!
themeName!accessing!public! !
!

