"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQFlickTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQFlickTheme guid: (GUID fromString: '{04aa8e14-1c05-4707-b2e1-2310911187eb}')!
JQFlickTheme comment: ''!
!JQFlickTheme categoriesForClass!JQuery-UI-Libraries! !
!JQFlickTheme methodsFor!

themeName	^ 'flick'! !
!JQFlickTheme categoriesFor: #themeName!accessing!public! !

