"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQFlickTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQFlickTheme guid: (GUID fromString: '{ec37daa0-2b87-4fc6-bd5f-392cdd940820}')!

JQFlickTheme comment: ''!

!JQFlickTheme categoriesForClass!JQuery-UI-Libraries! !

!JQFlickTheme methodsFor!

themeName	^ 'flick'! !

!JQFlickTheme categoriesForMethods!
themeName!accessing!public! !
!

