"Filed out from Dolphin Smalltalk 7"!

WAFileLibrary subclass: #JQGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQGoogleLibrary guid: (GUID fromString: '{5b0169a4-4975-47df-a50e-5f775f444ef6}')!
JQGoogleLibrary comment: ''!
!JQGoogleLibrary categoriesForClass!JQuery-Core-Libraries! !
!JQGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'! !
!JQGoogleLibrary categoriesFor: #updateRoot:!public!updating! !

