"Filed out from Dolphin Smalltalk"!

WAFileLibrary subclass: #JQGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQGoogleLibrary guid: (GUID fromString: '{8411a8a0-bbbe-44a3-b266-a603ad99abe8}')!

JQGoogleLibrary comment: ''!

!JQGoogleLibrary categoriesForClass!JQuery-Core-Libraries! !

!JQGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js'! !

!JQGoogleLibrary categoriesForMethods!
updateRoot:!public!updating! !
!

