"Filed out from Dolphin Smalltalk"!

WAFileLibrary subclass: #JQGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQGoogleLibrary guid: (GUID fromString: '{39667c27-8a39-4483-868a-264a506b1b0b}')!

JQGoogleLibrary comment: ''!

!JQGoogleLibrary categoriesForClass!Libraries! !

!JQGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js'! !

!JQGoogleLibrary categoriesForMethods!
updateRoot:!public!updating! !
!

