"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQHotSneaksTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQHotSneaksTheme guid: (GUID fromString: '{fff86b4e-0cbc-41b0-a567-aa7893abfa5c}')!

JQHotSneaksTheme comment: ''!

!JQHotSneaksTheme categoriesForClass!Libraries! !

!JQHotSneaksTheme methodsFor!

themeName	^ 'hot-sneaks'! !

!JQHotSneaksTheme categoriesForMethods!
themeName!accessing!public! !
!

