"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQHotSneaksTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQHotSneaksTheme guid: (GUID fromString: '{68279e4c-b1f1-41af-8924-833959e5e7ba}')!

JQHotSneaksTheme comment: ''!

!JQHotSneaksTheme categoriesForClass!JQuery-UI-Libraries! !

!JQHotSneaksTheme methodsFor!

themeName	^ 'hot-sneaks'! !

!JQHotSneaksTheme categoriesForMethods!
themeName!accessing!public! !
!

