"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQHotSneaksTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQHotSneaksTheme guid: (GUID fromString: '{2348491e-e1d0-4c8d-8b2c-94a89297ff4e}')!
JQHotSneaksTheme comment: ''!
!JQHotSneaksTheme categoriesForClass!JQuery-UI-Libraries! !
!JQHotSneaksTheme methodsFor!

themeName	^ 'hot-sneaks'! !
!JQHotSneaksTheme categoriesFor: #themeName!accessing!public! !

