"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQHumanityTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQHumanityTheme guid: (GUID fromString: '{0954af1c-f7dc-4995-a7f7-53f191024d09}')!

JQHumanityTheme comment: ''!

!JQHumanityTheme categoriesForClass!JQuery-UI-Libraries! !

!JQHumanityTheme methodsFor!

themeName	^ 'humanity'! !

!JQHumanityTheme categoriesForMethods!
themeName!accessing!public! !
!

