"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQHumanityTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQHumanityTheme guid: (GUID fromString: '{2c8597a9-1211-4d6d-bfc2-f3297879acf7}')!

JQHumanityTheme comment: ''!

!JQHumanityTheme categoriesForClass!Libraries! !

!JQHumanityTheme methodsFor!

themeName	^ 'humanity'! !

!JQHumanityTheme categoriesForMethods!
themeName!accessing!public! !
!

