"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQHumanityTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQHumanityTheme guid: (GUID fromString: '{d285c53c-3f43-49b6-bdb9-b85ad2840611}')!
JQHumanityTheme comment: ''!
!JQHumanityTheme categoriesForClass!JQuery-UI-Libraries! !
!JQHumanityTheme methodsFor!

themeName	^ 'humanity'! !
!JQHumanityTheme categoriesFor: #themeName!accessing!public! !

