"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQLeFrogTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQLeFrogTheme guid: (GUID fromString: '{fd71c6cc-2f17-484f-a10f-35a9802888a6}')!

JQLeFrogTheme comment: ''!

!JQLeFrogTheme categoriesForClass!JQuery-UI-Libraries! !

!JQLeFrogTheme methodsFor!

themeName	^ 'le-frog'! !

!JQLeFrogTheme categoriesForMethods!
themeName!accessing!public! !
!

