"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQLeFrogTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQLeFrogTheme guid: (GUID fromString: '{6164413f-868f-41bb-b313-b6301e840686}')!

JQLeFrogTheme comment: ''!

!JQLeFrogTheme categoriesForClass!Libraries! !

!JQLeFrogTheme methodsFor!

themeName	^ 'le-frog'! !

!JQLeFrogTheme categoriesForMethods!
themeName!accessing!public! !
!

