"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQLeFrogTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQLeFrogTheme guid: (GUID fromString: '{03d75307-fd94-40a0-ae30-d2a9c182eb78}')!
JQLeFrogTheme comment: ''!
!JQLeFrogTheme categoriesForClass!JQuery-UI-Libraries! !
!JQLeFrogTheme methodsFor!

themeName	^ 'le-frog'! !
!JQLeFrogTheme categoriesFor: #themeName!accessing!public! !

