"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQMintChocTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQMintChocTheme guid: (GUID fromString: '{6282596f-dd5f-41a5-9faa-c417c0385456}')!

JQMintChocTheme comment: ''!

!JQMintChocTheme categoriesForClass!JQuery-UI-Libraries! !

!JQMintChocTheme methodsFor!

themeName	^ 'mint-choc'! !

!JQMintChocTheme categoriesForMethods!
themeName!accessing!public! !
!

