"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQMintChocTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQMintChocTheme guid: (GUID fromString: '{69787ba5-2cd0-496e-9873-f691b03d1e23}')!
JQMintChocTheme comment: ''!
!JQMintChocTheme categoriesForClass!JQuery-UI-Libraries! !
!JQMintChocTheme methodsFor!

themeName	^ 'mint-choc'! !
!JQMintChocTheme categoriesFor: #themeName!accessing!public! !

