"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQMintChocTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQMintChocTheme guid: (GUID fromString: '{0fe68f24-503a-4c65-a1e7-764a49a84b4c}')!
JQMintChocTheme comment: ''!
!JQMintChocTheme categoriesForClass!JQuery-UI-Libraries! !
!JQMintChocTheme methodsFor!

themeName	^ 'mint-choc'! !
!JQMintChocTheme categoriesFor: #themeName!accessing!public! !

