"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQOvercastTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQOvercastTheme guid: (GUID fromString: '{d53c4bc8-b82e-4557-ab34-56972112ea19}')!

JQOvercastTheme comment: ''!

!JQOvercastTheme categoriesForClass!JQuery-UI-Libraries! !

!JQOvercastTheme methodsFor!

themeName	^ 'overcast'! !

!JQOvercastTheme categoriesForMethods!
themeName!accessing!public! !
!

