"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQOvercastTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQOvercastTheme guid: (GUID fromString: '{7966118b-e40a-4d06-b829-a5dca628eb20}')!

JQOvercastTheme comment: ''!

!JQOvercastTheme categoriesForClass!Libraries! !

!JQOvercastTheme methodsFor!

themeName	^ 'overcast'! !

!JQOvercastTheme categoriesForMethods!
themeName!accessing!public! !
!

