"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQOvercastTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQOvercastTheme guid: (GUID fromString: '{323678da-d930-46a2-b540-5946d8071e04}')!
JQOvercastTheme comment: ''!
!JQOvercastTheme categoriesForClass!JQuery-UI-Libraries! !
!JQOvercastTheme methodsFor!

themeName	^ 'overcast'! !
!JQOvercastTheme categoriesFor: #themeName!accessing!public! !

