"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQPepperGrinderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQPepperGrinderTheme guid: (GUID fromString: '{70d3dc2e-223b-49c5-9ac2-370145767010}')!

JQPepperGrinderTheme comment: ''!

!JQPepperGrinderTheme categoriesForClass!Libraries! !

!JQPepperGrinderTheme methodsFor!

themeName	^ 'pepper-grinder'! !

!JQPepperGrinderTheme categoriesForMethods!
themeName!accessing!public! !
!

