"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQPepperGrinderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQPepperGrinderTheme guid: (GUID fromString: '{f43e91cb-02b8-4462-947f-28f079b845ac}')!
JQPepperGrinderTheme comment: ''!
!JQPepperGrinderTheme categoriesForClass!JQuery-UI-Libraries! !
!JQPepperGrinderTheme methodsFor!

themeName	^ 'pepper-grinder'! !
!JQPepperGrinderTheme categoriesFor: #themeName!accessing!public! !

