"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQPepperGrinderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQPepperGrinderTheme guid: (GUID fromString: '{80018bb0-bf0e-4c4b-80ef-3973dc989b87}')!

JQPepperGrinderTheme comment: ''!

!JQPepperGrinderTheme categoriesForClass!JQuery-UI-Libraries! !

!JQPepperGrinderTheme methodsFor!

themeName	^ 'pepper-grinder'! !

!JQPepperGrinderTheme categoriesForMethods!
themeName!accessing!public! !
!

