"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQRedmondTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQRedmondTheme guid: (GUID fromString: '{79059e21-a6d8-437d-89c5-3c2b33444857}')!

JQRedmondTheme comment: ''!

!JQRedmondTheme categoriesForClass!Libraries! !

!JQRedmondTheme methodsFor!

themeName	^ 'redmond'! !

!JQRedmondTheme categoriesForMethods!
themeName!accessing!public! !
!

