"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQRedmondTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQRedmondTheme guid: (GUID fromString: '{17a9741d-36d5-401d-b227-e18e88bc2983}')!

JQRedmondTheme comment: ''!

!JQRedmondTheme categoriesForClass!JQuery-UI-Libraries! !

!JQRedmondTheme methodsFor!

themeName	^ 'redmond'! !

!JQRedmondTheme categoriesForMethods!
themeName!accessing!public! !
!

