"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQRedmondTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQRedmondTheme guid: (GUID fromString: '{b9fca9d3-8347-4bb1-9ac6-23272c59af32}')!
JQRedmondTheme comment: ''!
!JQRedmondTheme categoriesForClass!JQuery-UI-Libraries! !
!JQRedmondTheme methodsFor!

themeName	^ 'redmond'! !
!JQRedmondTheme categoriesFor: #themeName!accessing!public! !

