"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSmoothnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSmoothnessTheme guid: (GUID fromString: '{571777ad-a58a-4194-85a3-062485f064e5}')!

JQSmoothnessTheme comment: ''!

!JQSmoothnessTheme categoriesForClass!Libraries! !

!JQSmoothnessTheme methodsFor!

themeName	^ 'smoothness'! !

!JQSmoothnessTheme categoriesForMethods!
themeName!accessing!public! !
!

