"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQSmoothnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQSmoothnessTheme guid: (GUID fromString: '{fd543481-22c2-42c8-98ca-dd52130bf4c2}')!
JQSmoothnessTheme comment: ''!
!JQSmoothnessTheme categoriesForClass!JQuery-UI-Libraries! !
!JQSmoothnessTheme methodsFor!

themeName	^ 'smoothness'! !
!JQSmoothnessTheme categoriesFor: #themeName!accessing!public! !

