"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSmoothnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSmoothnessTheme guid: (GUID fromString: '{9bee35ef-4d29-4d4b-853b-c33717d7c3be}')!

JQSmoothnessTheme comment: ''!

!JQSmoothnessTheme categoriesForClass!JQuery-UI-Libraries! !

!JQSmoothnessTheme methodsFor!

themeName	^ 'smoothness'! !

!JQSmoothnessTheme categoriesForMethods!
themeName!accessing!public! !
!

