"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSouthStreetTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSouthStreetTheme guid: (GUID fromString: '{27abe289-c8ab-4d1d-9fc7-ae561af25d92}')!

JQSouthStreetTheme comment: ''!

!JQSouthStreetTheme categoriesForClass!Libraries! !

!JQSouthStreetTheme methodsFor!

themeName	^ 'south-street'! !

!JQSouthStreetTheme categoriesForMethods!
themeName!accessing!public! !
!

