"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQSouthStreetTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQSouthStreetTheme guid: (GUID fromString: '{d121a962-44e5-42a0-bdbe-602cd1049a26}')!
JQSouthStreetTheme comment: ''!
!JQSouthStreetTheme categoriesForClass!JQuery-UI-Libraries! !
!JQSouthStreetTheme methodsFor!

themeName	^ 'south-street'! !
!JQSouthStreetTheme categoriesFor: #themeName!accessing!public! !

