"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSouthStreetTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSouthStreetTheme guid: (GUID fromString: '{49f4c984-edfc-46f9-a8df-8f7a87a6ac6b}')!

JQSouthStreetTheme comment: ''!

!JQSouthStreetTheme categoriesForClass!JQuery-UI-Libraries! !

!JQSouthStreetTheme methodsFor!

themeName	^ 'south-street'! !

!JQSouthStreetTheme categoriesForMethods!
themeName!accessing!public! !
!

