"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQStartTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQStartTheme guid: (GUID fromString: '{22baf995-8856-44fe-b093-d4d08d2aae1a}')!

JQStartTheme comment: ''!

!JQStartTheme categoriesForClass!Libraries! !

!JQStartTheme methodsFor!

themeName	^ 'start'! !

!JQStartTheme categoriesForMethods!
themeName!accessing!public! !
!

