"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQStartTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQStartTheme guid: (GUID fromString: '{9938f6d8-2cc4-409f-afdc-89a004174dde}')!
JQStartTheme comment: ''!
!JQStartTheme categoriesForClass!JQuery-UI-Libraries! !
!JQStartTheme methodsFor!

themeName	^ 'start'! !
!JQStartTheme categoriesFor: #themeName!accessing!public! !

