"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQStartTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQStartTheme guid: (GUID fromString: '{34888c52-f8a0-4861-a380-2457aed255ee}')!

JQStartTheme comment: ''!

!JQStartTheme categoriesForClass!JQuery-UI-Libraries! !

!JQStartTheme methodsFor!

themeName	^ 'start'! !

!JQStartTheme categoriesForMethods!
themeName!accessing!public! !
!

