"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSunnyTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSunnyTheme guid: (GUID fromString: '{c52cd23b-4df7-4902-8af9-7f4853d2c582}')!

JQSunnyTheme comment: ''!

!JQSunnyTheme categoriesForClass!JQuery-UI-Libraries! !

!JQSunnyTheme methodsFor!

themeName	^ 'sunny'! !

!JQSunnyTheme categoriesForMethods!
themeName!accessing!public! !
!

