"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQSunnyTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQSunnyTheme guid: (GUID fromString: '{e728c826-f67c-448d-975b-7b11a3bfad06}')!
JQSunnyTheme comment: ''!
!JQSunnyTheme categoriesForClass!JQuery-UI-Libraries! !
!JQSunnyTheme methodsFor!

themeName	^ 'sunny'! !
!JQSunnyTheme categoriesFor: #themeName!accessing!public! !

