"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQSunnyTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQSunnyTheme guid: (GUID fromString: '{6f96b1a5-e0db-45c4-a615-f70cd03cab3e}')!
JQSunnyTheme comment: ''!
!JQSunnyTheme categoriesForClass!JQuery-UI-Libraries! !
!JQSunnyTheme methodsFor!

themeName	^ 'sunny'! !
!JQSunnyTheme categoriesFor: #themeName!accessing!public! !

