"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQSwankyPurseTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQSwankyPurseTheme guid: (GUID fromString: '{c3361421-0893-4878-9d42-4bac99c85cae}')!
JQSwankyPurseTheme comment: ''!
!JQSwankyPurseTheme categoriesForClass!JQuery-UI-Libraries! !
!JQSwankyPurseTheme methodsFor!

themeName	^ 'swanky-purse'! !
!JQSwankyPurseTheme categoriesFor: #themeName!accessing!public! !

