"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSwankyPurseTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSwankyPurseTheme guid: (GUID fromString: '{4c5d88d2-bba7-441d-affd-19b8a7431b7f}')!

JQSwankyPurseTheme comment: ''!

!JQSwankyPurseTheme categoriesForClass!JQuery-UI-Libraries! !

!JQSwankyPurseTheme methodsFor!

themeName	^ 'swanky-purse'! !

!JQSwankyPurseTheme categoriesForMethods!
themeName!accessing!public! !
!

