"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQSwankyPurseTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQSwankyPurseTheme guid: (GUID fromString: '{110ec827-cf17-4ce5-b5c8-200610810083}')!

JQSwankyPurseTheme comment: ''!

!JQSwankyPurseTheme categoriesForClass!Libraries! !

!JQSwankyPurseTheme methodsFor!

themeName	^ 'swanky-purse'! !

!JQSwankyPurseTheme categoriesForMethods!
themeName!accessing!public! !
!

