"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQTrontasticTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQTrontasticTheme guid: (GUID fromString: '{fe01bb26-6c20-41c5-8fe9-0843d9dd86a0}')!

JQTrontasticTheme comment: ''!

!JQTrontasticTheme categoriesForClass!JQuery-UI-Libraries! !

!JQTrontasticTheme methodsFor!

themeName	^ 'trontastic'! !

!JQTrontasticTheme categoriesForMethods!
themeName!accessing!public! !
!

