"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQTrontasticTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQTrontasticTheme guid: (GUID fromString: '{a8a89111-8840-46af-bfc7-d2930bc5a0d7}')!
JQTrontasticTheme comment: ''!
!JQTrontasticTheme categoriesForClass!JQuery-UI-Libraries! !
!JQTrontasticTheme methodsFor!

themeName	^ 'trontastic'! !
!JQTrontasticTheme categoriesFor: #themeName!accessing!public! !

