"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQTrontasticTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQTrontasticTheme guid: (GUID fromString: '{9851573c-c9de-460c-a992-42ea133de79c}')!
JQTrontasticTheme comment: ''!
!JQTrontasticTheme categoriesForClass!JQuery-UI-Libraries! !
!JQTrontasticTheme methodsFor!

themeName	^ 'trontastic'! !
!JQTrontasticTheme categoriesFor: #themeName!accessing!public! !

