"Filed out from Dolphin Smalltalk 7"!

JQueryTest subclass: #JQueryUiTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQueryUiTest guid: (GUID fromString: '{4b386126-7154-49e8-99f8-da6897b62129}')!
JQueryUiTest comment: ''!
!JQueryUiTest categoriesForClass!JQuery-Tests-UI-Unit! !
!JQueryUiTest class methodsFor!

isAbstract	^ self name = #JQueryUiTest!

packageNamesUnderTest	^ #('JQuery-UI')! !
!JQueryUiTest class categoriesFor: #isAbstract!public!testing! !
!JQueryUiTest class categoriesFor: #packageNamesUnderTest!accessing!public! !

