"Filed out from Dolphin Smalltalk 7"!

JQueryTest subclass: #JQueryUiTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQueryUiTest guid: (GUID fromString: '{eb0a69a7-ae0d-4835-a6bf-a69324d641fd}')!
JQueryUiTest comment: ''!
!JQueryUiTest categoriesForClass!JQuery-Tests-UI-Unit! !
!JQueryUiTest class methodsFor!

isAbstract	^ self name = #JQueryUiTest!

packageNamesUnderTest	^ #('JQuery-UI')! !
!JQueryUiTest class categoriesFor: #isAbstract!public!testing! !
!JQueryUiTest class categoriesFor: #packageNamesUnderTest!accessing!public! !

