"Filed out from Dolphin Smalltalk"!

JQueryTest subclass: #JQueryUiTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQueryUiTest guid: (GUID fromString: '{29ab24bd-c2cf-419c-a53e-adcb0d2f0d9c}')!

JQueryUiTest comment: ''!

!JQueryUiTest categoriesForClass!Unit! !

!JQueryUiTest class methodsFor!

isAbstract	^ self name = #JQueryUiTest!

packageNamesUnderTest	^ #('JQuery-UI')! !

!JQueryUiTest class categoriesForMethods!
isAbstract!public!testing! !
packageNamesUnderTest!accessing!public! !
!

