"Filed out from Dolphin Smalltalk 7"!

WAFileLibrary subclass: #JQUiGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQUiGoogleLibrary guid: (GUID fromString: '{acaa47c5-6103-4fd1-8444-f87e1f1d89e3}')!
JQUiGoogleLibrary comment: ''!
!JQUiGoogleLibrary categoriesForClass!JQuery-UI-Libraries! !
!JQUiGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js'! !
!JQUiGoogleLibrary categoriesFor: #updateRoot:!public!updating! !

