"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQUiDarknessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQUiDarknessTheme guid: (GUID fromString: '{3ca174af-c6be-4613-a5fe-798b82fbbef4}')!

JQUiDarknessTheme comment: ''!

!JQUiDarknessTheme categoriesForClass!Libraries! !

!JQUiDarknessTheme methodsFor!

themeName	^ 'ui-darkness'! !

!JQUiDarknessTheme categoriesForMethods!
themeName!accessing!public! !
!

