"Filed out from Dolphin Smalltalk"!

WAFileLibrary subclass: #JQUiGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQUiGoogleLibrary guid: (GUID fromString: '{fe24745b-1f8a-415b-90cb-c74ca11b3743}')!

JQUiGoogleLibrary comment: ''!

!JQUiGoogleLibrary categoriesForClass!JQuery-UI-Libraries! !

!JQUiGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js'! !

!JQUiGoogleLibrary categoriesForMethods!
updateRoot:!public!updating! !
!

