"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQUiLightnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQUiLightnessTheme guid: (GUID fromString: '{0ed9d3f5-a595-4d8b-b2d7-c7b0484b286b}')!
JQUiLightnessTheme comment: ''!
!JQUiLightnessTheme categoriesForClass!JQuery-UI-Libraries! !
!JQUiLightnessTheme methodsFor!

themeName	^ 'ui-lightness'! !
!JQUiLightnessTheme categoriesFor: #themeName!accessing!public! !

