"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQUiLightnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQUiLightnessTheme guid: (GUID fromString: '{3a01eb86-222e-4c95-b49c-6e4166fab9cc}')!
JQUiLightnessTheme comment: ''!
!JQUiLightnessTheme categoriesForClass!JQuery-UI-Libraries! !
!JQUiLightnessTheme methodsFor!

themeName	^ 'ui-lightness'! !
!JQUiLightnessTheme categoriesFor: #themeName!accessing!public! !

