"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQUiDarknessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQUiDarknessTheme guid: (GUID fromString: '{74e9a157-cce4-4cdf-a04e-acc353e39300}')!

JQUiDarknessTheme comment: ''!

!JQUiDarknessTheme categoriesForClass!JQuery-UI-Libraries! !

!JQUiDarknessTheme methodsFor!

themeName	^ 'ui-darkness'! !

!JQUiDarknessTheme categoriesForMethods!
themeName!accessing!public! !
!

