"Filed out from Dolphin Smalltalk"!

WAFileLibrary subclass: #JQUiGoogleLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQUiGoogleLibrary guid: (GUID fromString: '{5aa1af58-d853-4c31-b0dc-c15f8eab05d5}')!

JQUiGoogleLibrary comment: ''!

!JQUiGoogleLibrary categoriesForClass!Libraries! !

!JQUiGoogleLibrary methodsFor!

updateRoot: anHtmlRoot	super updateRoot: anHtmlRoot.	anHtmlRoot javascript		url: 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js'! !

!JQUiGoogleLibrary categoriesForMethods!
updateRoot:!public!updating! !
!

