"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQUiDarknessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQUiDarknessTheme guid: (GUID fromString: '{8102de53-65e9-482b-a606-1a3946e89e09}')!
JQUiDarknessTheme comment: ''!
!JQUiDarknessTheme categoriesForClass!JQuery-UI-Libraries! !
!JQUiDarknessTheme methodsFor!

themeName	^ 'ui-darkness'! !
!JQUiDarknessTheme categoriesFor: #themeName!accessing!public! !

