"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQUiLightnessTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQUiLightnessTheme guid: (GUID fromString: '{135394d6-476f-4f27-8060-a54d8481f778}')!

JQUiLightnessTheme comment: ''!

!JQUiLightnessTheme categoriesForClass!Libraries! !

!JQUiLightnessTheme methodsFor!

themeName	^ 'ui-lightness'! !

!JQUiLightnessTheme categoriesForMethods!
themeName!accessing!public! !
!

