"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQVaderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQVaderTheme guid: (GUID fromString: '{575228f1-ec60-45b7-a897-214d2097f7a0}')!
JQVaderTheme comment: ''!
!JQVaderTheme categoriesForClass!JQuery-UI-Libraries! !
!JQVaderTheme methodsFor!

themeName	^ 'vader'! !
!JQVaderTheme categoriesFor: #themeName!accessing!public! !

