"Filed out from Dolphin Smalltalk"!

JQBaseTheme subclass: #JQVaderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JQVaderTheme guid: (GUID fromString: '{528aa55e-769c-46bd-9a2c-af6c045e3cda}')!

JQVaderTheme comment: ''!

!JQVaderTheme categoriesForClass!Libraries! !

!JQVaderTheme methodsFor!

themeName	^ 'vader'! !

!JQVaderTheme categoriesForMethods!
themeName!accessing!public! !
!

