"Filed out from Dolphin Smalltalk 7"!

JQBaseTheme subclass: #JQVaderTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JQVaderTheme guid: (GUID fromString: '{9bde038b-b324-4814-b8cc-235e0c1daf09}')!
JQVaderTheme comment: ''!
!JQVaderTheme categoriesForClass!JQuery-UI-Libraries! !
!JQVaderTheme methodsFor!

themeName	^ 'vader'! !
!JQVaderTheme categoriesFor: #themeName!accessing!public! !

