"Filed out from Dolphin Smalltalk 7"!

File subclass: #FileSystem
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FileSystem guid: (GUID fromString: '{c5bbbcec-b518-49f4-a801-195bbfddd925}')!
FileSystem comment: ''!
!FileSystem categoriesForClass!System-Support! !
!FileSystem class methodsFor!

workingDirectory

	^super workingDirectory asFileReference! !
!FileSystem class categoriesFor: #workingDirectory!public! !

