"Filed out from Dolphin Smalltalk 7"!

GRDelegatingStream subclass: #GRCodecStream
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRCodecStream guid: (GUID fromString: '{5f3e52a3-2094-4a77-92bb-287a2a31cd7e}')!
GRCodecStream comment: 'GRCodecStream is the abstract base class for codec streams'!
!GRCodecStream categoriesForClass!Grease-Core-Text! !
