"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRErrorStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRErrorStub guid: (GUID fromString: '{1cb1c418-199a-4015-a2b8-43848112f56f}')!
GRErrorStub comment: ''!
!GRErrorStub categoriesForClass!Grease-Tests-Core! !
!GRErrorStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRErrorStub categoriesFor: #foo!accessing!public! !
!GRErrorStub categoriesFor: #initialize!initialization!public! !

