"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRInvalidArgumentCount
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRInvalidArgumentCount guid: (GUID fromString: '{08ac9645-425a-47d0-9d26-45f57ead0f46}')!
GRInvalidArgumentCount comment: 'Signaled whenever a message is sent with the incorrect number of arguments.'!
!GRInvalidArgumentCount categoriesForClass!Grease-Core-Utilities! !
