"Filed out from Dolphin Smalltalk 7"!

GRNotification subclass: #GRNotificationStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRNotificationStub guid: (GUID fromString: '{67d2b75a-b8b7-4ca8-90d3-eeabe709a672}')!
GRNotificationStub comment: ''!
!GRNotificationStub categoriesForClass!Grease-Tests-Core! !
!GRNotificationStub methodsFor!

defaultAction	^ #returnValue!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRNotificationStub categoriesFor: #defaultAction!accessing!public! !
!GRNotificationStub categoriesFor: #foo!accessing!public! !
!GRNotificationStub categoriesFor: #initialize!initialization!public! !

