"Filed out from Dolphin Smalltalk 7"!

GRObject subclass: #GRObjectStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRObjectStub guid: (GUID fromString: '{5950e5b7-5057-49ca-99e2-60210c98d90b}')!
GRObjectStub comment: ''!
!GRObjectStub categoriesForClass!Grease-Tests-Core! !
!GRObjectStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRObjectStub categoriesFor: #foo!accessing!public! !
!GRObjectStub categoriesFor: #initialize!initialization!public! !

