"Filed out from Dolphin Smalltalk 7"!

String variableByteSubclass: #Text
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Text guid: (GUID fromString: '{f870fbfd-f333-4566-83fd-9ebb426fa397}')!
Text isNullTerminated: true!
Text comment: ''!
!Text categoriesForClass!Collections-Text! !
!Text methodsFor!

string

	^self! !
!Text categoriesFor: #string!public! !

!Text class methodsFor!

fromString: aString

	^aString copy! !
!Text class categoriesFor: #fromString:!public! !

