"Filed out from Dolphin Smalltalk"!

JSMember subclass: #JSAlias
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSAlias guid: (GUID fromString: '{4c930356-4e3e-470f-89d7-220f1a67aec1}')!

JSAlias comment: 'I alias the decorated object with a name.'!

!JSAlias categoriesForClass!Javascript-Core-Decorations! !

!JSAlias methodsFor!

javascriptContentOn: aRenderer	aRenderer document identifier: self name! !

!JSAlias categoriesForMethods!
javascriptContentOn:!printing!public! !
!

