"Filed out from Dolphin Smalltalk"!

JSJavascriptElementBrush subclass: #JSJavascriptValueBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptValueBrush guid: (GUID fromString: '{ce7aea96-1cbb-46fe-b749-0ba1243fe298}')!

JSJavascriptValueBrush comment: 'A JSON value'!

!JSJavascriptValueBrush categoriesForClass!Javascript-Core-Brushes! !

