"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavascriptArrayBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptArrayBrush guid: (GUID fromString: '{f26cc043-694f-41c2-b793-d9412a3bee58}')!

JSJavascriptArrayBrush comment: 'Brush for a JSON array'!

!JSJavascriptArrayBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavascriptArrayBrush methodsFor!

closeBrush	self document closeArray!

openBrush	self document openArray! !

!JSJavascriptArrayBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

