"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavascriptFunctionArgumentBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptFunctionArgumentBrush guid: (GUID fromString: '{612358d8-9d7c-43e4-b455-97bee2cda252}')!

JSJavascriptFunctionArgumentBrush comment: ''!

!JSJavascriptFunctionArgumentBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavascriptFunctionArgumentBrush methodsFor!

closeBrush!

openBrush	canvas writeCharacterIfNotFirst: $,! !

!JSJavascriptFunctionArgumentBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

