"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavasciptObjectBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavasciptObjectBrush guid: (GUID fromString: '{aa0fb8ef-8e69-46f4-9a85-48f894fb5a2e}')!

JSJavasciptObjectBrush comment: 'A brush to generate a JSON object'!

!JSJavasciptObjectBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavasciptObjectBrush methodsFor!

closeBrush	self document closeObject!

openBrush	self document openObject! !

!JSJavasciptObjectBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

