"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavascriptFunctionArgumentsBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptFunctionArgumentsBrush guid: (GUID fromString: '{24b8874a-0992-4d23-8855-a3b943a067a8}')!

JSJavascriptFunctionArgumentsBrush comment: ''!

!JSJavascriptFunctionArgumentsBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavascriptFunctionArgumentsBrush methodsFor!

closeBrush	self document nextPut: $)!

openBrush	self document nextPut: $(! !

!JSJavascriptFunctionArgumentsBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

