"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavascriptReturnBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptReturnBrush guid: (GUID fromString: '{dabbc566-9a60-46cf-a703-3f48c4b739b3}')!

JSJavascriptReturnBrush comment: ''!

!JSJavascriptReturnBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavascriptReturnBrush methodsFor!

closeBrush!

openBrush	self document keyword: 'return'! !

!JSJavascriptReturnBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

