"Filed out from Dolphin Smalltalk"!

JSJavascriptBrush subclass: #JSJavascriptAssignmentBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSJavascriptAssignmentBrush guid: (GUID fromString: '{b80bdb7f-4982-48ff-9136-bdbe636c4e94}')!

JSJavascriptAssignmentBrush comment: ''!

!JSJavascriptAssignmentBrush categoriesForClass!Javascript-Core-Brushes! !

!JSJavascriptAssignmentBrush methodsFor!

closeBrush!

openBrush	self document assignment! !

!JSJavascriptAssignmentBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

