"Filed out from Dolphin Smalltalk"!

JSDecoration subclass: #JSNegation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSNegation guid: (GUID fromString: '{73ecc4db-af17-48fb-a7ea-72875afba5d9}')!

JSNegation comment: 'I negate the decorated object and yield a boolean value.'!

!JSNegation categoriesForClass!Javascript-Core-Decorations! !

!JSNegation methodsFor!

javascriptContentOn: aRenderer	aRenderer document negation.	super javascriptContentOn: aRenderer! !

!JSNegation categoriesForMethods!
javascriptContentOn:!printing!public! !
!

