"Filed out from Dolphin Smalltalk"!

JSDecoration subclass: #JSStatement
	instanceVariableNames: 'statement'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSStatement guid: (GUID fromString: '{5e676942-5b82-4b6e-ae80-9b424d128c06}')!

JSStatement comment: ''!

!JSStatement categoriesForClass!Decorations! !

!JSStatement methodsFor!

statement	^ statement!

statement: anObject	statement := anObject! !

!JSStatement categoriesForMethods!
statement!accessing!public! !
statement:!accessing!public! !
!

!JSStatement class methodsFor!

on: anObject	^ self new statement: anObject! !

!JSStatement class categoriesForMethods!
on:!instance creation!public! !
!

