"Filed out from Dolphin Smalltalk"!

JSDecoration subclass: #JSStatement
	instanceVariableNames: 'statement'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSStatement guid: (GUID fromString: '{28231d6a-a194-4c53-a684-418fb27dae10}')!

JSStatement comment: ''!

!JSStatement categoriesForClass!Javascript-Core-Decorations! !

!JSStatement methodsFor!

statement	^ statement!

statement: anObject	statement := anObject! !

!JSStatement categoriesForMethods!
statement!accessing!public! !
statement:!accessing!public! !
!

!JSStatement class methodsFor!

on: anObject	^ self new statement: anObject! !

!JSStatement class categoriesForMethods!
on:!instance creation!public! !
!

