"Filed out from Dolphin Smalltalk"!

JSDecoration subclass: #JSTimed
	instanceVariableNames: 'duration'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSTimed guid: (GUID fromString: '{9b179408-532e-40fe-97e9-77f99d2b2afc}')!

JSTimed comment: ''!

!JSTimed categoriesForClass!Decorations! !

!JSTimed methodsFor!

duration	^ duration!

duration: aDuration	duration := aDuration! !

!JSTimed categoriesForMethods!
duration!accessing!public! !
duration:!accessing!public! !
!

!JSTimed class methodsFor!

duration: aDuration	^ self new duration: aDuration! !

!JSTimed class categoriesForMethods!
duration:!instance creation!public! !
!

