"Filed out from Dolphin Smalltalk"!

JSDecoration subclass: #JSTimed
	instanceVariableNames: 'duration'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

JSTimed guid: (GUID fromString: '{37c8eb11-fdc0-40fc-be78-d04cfb47b2f7}')!

JSTimed comment: ''!

!JSTimed categoriesForClass!Javascript-Core-Decorations! !

!JSTimed methodsFor!

duration	^ duration!

duration: aDuration	duration := aDuration! !

!JSTimed categoriesForMethods!
duration!accessing!public! !
duration:!accessing!public! !
!

!JSTimed class methodsFor!

duration: aDuration	^ self new duration: aDuration! !

!JSTimed class categoriesForMethods!
duration:!instance creation!public! !
!

