"Filed out from Dolphin Smalltalk 7"!

JSDecoration subclass: #JSTimed
	instanceVariableNames: 'duration'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JSTimed guid: (GUID fromString: '{65014967-90d7-42fe-a48a-eb866a3be4d0}')!
JSTimed comment: ''!
!JSTimed categoriesForClass!Javascript-Core-Decorations! !
!JSTimed methodsFor!

duration	^ duration!

duration: aDuration	duration := aDuration! !
!JSTimed categoriesFor: #duration!accessing!public! !
!JSTimed categoriesFor: #duration:!accessing!public! !

!JSTimed class methodsFor!

duration: aDuration	^ self new duration: aDuration! !
!JSTimed class categoriesFor: #duration:!instance creation!public! !

