"Filed out from Dolphin Smalltalk"!

PackageManifest subclass: #ManifestJavascriptCore
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

ManifestJavascriptCore guid: (GUID fromString: '{39ca0924-3ef8-41a5-a562-9943288ba332}')!

ManifestJavascriptCore comment: 'Please describe the package using the class comment of the included manifest class. The manifest class also includes other additional metadata for the package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser'!

!ManifestJavascriptCore categoriesForClass!Manifest! !

!ManifestJavascriptCore class methodsFor!

ruleTempsReadBeforeWrittenRuleV1FalsePositive	##(Pragma ignoreForCoverage).	^ #(#(#(#RGMethodDefinition #(#'JSStream class' #encodeString:on: #true)) #'2023-09-27T18:22:24.916405+02:00') )! !

!ManifestJavascriptCore class categoriesForMethods!
ruleTempsReadBeforeWrittenRuleV1FalsePositive!code/critics!public! !
!

