"Filed out from Dolphin Smalltalk 7"!

GRAbstractSequenceableCollectionTest subclass: #GRArrayTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRArrayTest guid: (GUID fromString: '{c36fcc2d-8e60-4557-9fc8-aa727ad044be}')!
GRArrayTest comment: ''!
!GRArrayTest categoriesForClass!Grease-Tests-Core! !
!GRArrayTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Array!

isExtensible	^ false!

isHomogeneous	^ false!

isInitializable	^ true!

isSequenced	^ true!

isUnique	^ false! !
!GRArrayTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRArrayTest categoriesFor: #collectionClass!configuration!public! !
!GRArrayTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRArrayTest categoriesFor: #isHomogeneous!public!testing! !
!GRArrayTest categoriesFor: #isInitializable!public!testing/ansi! !
!GRArrayTest categoriesFor: #isSequenced!public!testing/ansi! !
!GRArrayTest categoriesFor: #isUnique!public!testing! !

