"Filed out from Dolphin Smalltalk 7"!

GRCollectionTest subclass: #GRBagTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRBagTest guid: (GUID fromString: '{0a2fc4c1-fc8e-4372-a122-55e7fb84cc1e}')!
GRBagTest comment: ''!
!GRBagTest categoriesForClass!Grease-Tests-Core! !
!GRBagTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Bag!

isExtensible	^ true!

isInitializable	^ true! !
!GRBagTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRBagTest categoriesFor: #collectionClass!configuration!public! !
!GRBagTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRBagTest categoriesFor: #isInitializable!public!testing/ansi! !

