"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRInvalidUtf8Error
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRInvalidUtf8Error guid: (GUID fromString: '{d49f3318-437f-4f0c-8775-fe0c2f5fa43d}')!
GRInvalidUtf8Error comment: 'A WAInvalidUtf8Error signals that the input is not valid UTF-8.'!
!GRInvalidUtf8Error categoriesForClass!Grease-Core-Text! !
