"Filed out from Dolphin Smalltalk 7"!

Notification subclass: #GRNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRNotification guid: (GUID fromString: '{28553669-eb51-4e4f-813d-10e3296f4684}')!
GRNotification comment: 'This class provides consistent initialization and exception signaling behaviour across platforms. All platforms must provide the ANSI-standard signaling protocol on this class. #signal: can therefore be safely called on any subclass.Packages that are using Seaside-Platform should usually subclass GRNotification instead of Notification.'!
!GRNotification categoriesForClass!Grease-Core-Exceptions! !
