"Filed out from Dolphin Smalltalk 7"!

GRCollectionTest subclass: #GRSetTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRSetTest guid: (GUID fromString: '{168cf2cc-fce9-4ef0-b504-4f1db4153550}')!
GRSetTest comment: ''!
!GRSetTest categoriesForClass!Grease-Tests-Core! !
!GRSetTest methodsFor!

allowsDuplicateValues	^ false!

collectionClass	^ Set!

isExtensible	^ true!

isInitializable	^ true! !
!GRSetTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRSetTest categoriesFor: #collectionClass!configuration!public! !
!GRSetTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRSetTest categoriesFor: #isInitializable!public!testing/ansi! !

