"Filed out from Dolphin Smalltalk 7"!

GRAbstractSequenceableCollectionTest subclass: #GRSortedCollectionTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRSortedCollectionTest guid: (GUID fromString: '{a0545549-2737-473f-903e-59a215a1eecd}')!
GRSortedCollectionTest comment: ''!
!GRSortedCollectionTest categoriesForClass!Grease-Tests-Core! !
!GRSortedCollectionTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ SortedCollection!

isExtensible	^ true!

isHomogeneous	^ true!

isInitializable	^ true!

isSequenced	^ false!

isUnique	^ false! !
!GRSortedCollectionTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRSortedCollectionTest categoriesFor: #collectionClass!configuration!public! !
!GRSortedCollectionTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRSortedCollectionTest categoriesFor: #isHomogeneous!public!testing! !
!GRSortedCollectionTest categoriesFor: #isInitializable!public!testing/ansi! !
!GRSortedCollectionTest categoriesFor: #isSequenced!public!testing/ansi! !
!GRSortedCollectionTest categoriesFor: #isUnique!public!testing! !

