"Filed out from Dolphin Smalltalk 7"!

String variableByteSubclass: #Text
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Text guid: (GUID fromString: '{51463927-9382-401d-9718-e09a78c7c0a1}')!
Text isNullTerminated: true!
Text comment: ''!
!Text categoriesForClass!Unclassified! !
!Text methodsFor!

greaseString
	^self displayString! !
!Text categoriesFor: #greaseString!public! !

