"Filed out from Dolphin Smalltalk 7"!

WARequestFilter subclass: #WAAbstractProtectionFilter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAbstractProtectionFilter guid: (GUID fromString: '{aee9ca77-c4bd-43a1-9cfd-a0b97ca135c1}')!
WAAbstractProtectionFilter comment: 'WARequestFilter subclass: #WAAuthenticationFilter	instanceVariableNames: ''authenticator realm''	classVariableNames: ''''	package: ''Seaside-Core-Filter'''!
!WAAbstractProtectionFilter categoriesForClass!Seaside-Core-Filter! !
