"Filed out from Dolphin Smalltalk 7"!

WAQualifiedValue subclass: #WAAcceptEncoding
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAcceptEncoding guid: (GUID fromString: '{8d1c216a-5b35-4da7-b274-bce860a06338}')!
WAAcceptEncoding comment: 'WAAcceptEncoding class	instanceVariableNames: '''''!
!WAAcceptEncoding categoriesForClass!Seaside-Core-HTTP! !
!WAAcceptEncoding class methodsFor!

valueClass	^ String! !
!WAAcceptEncoding class categoriesFor: #valueClass!private! !

