"Filed out from Dolphin Smalltalk"!

WAQualifiedValue subclass: #WAAcceptLanguage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAcceptLanguage guid: (GUID fromString: '{5aab6a2d-da40-42d3-8180-211d55f32ef3}')!

WAAcceptLanguage comment: 'A WAAcceptLanguage is a WAQualifiedValue with a value that is an instance of WALocale. It represents how much a user agent prefers a certain locale.'!

!WAAcceptLanguage categoriesForClass!Seaside-Core-HTTP! !

!WAAcceptLanguage class methodsFor!

valueClass	^ WALocale! !

!WAAcceptLanguage class categoriesForMethods!
valueClass!private! !
!

