"Filed out from Dolphin Smalltalk"!

WAQualifiedValue subclass: #WAAcceptEncoding
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAcceptEncoding guid: (GUID fromString: '{933430d9-43fe-476f-9741-fb64ac81ecc3}')!

WAAcceptEncoding comment: 'A WAAcceptCharset is a WAQualifiedValue with a value that is an instance of String. It represents how much a user agent prefers a certain encoding for the response.'!

!WAAcceptEncoding categoriesForClass!HTTP! !

!WAAcceptEncoding class methodsFor!

valueClass	^ String! !

!WAAcceptEncoding class categoriesForMethods!
valueClass!private! !
!

