"Filed out from Dolphin Smalltalk"!

WAQualifiedValue subclass: #WAAcceptCharset
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAcceptCharset guid: (GUID fromString: '{7233d1c9-1af0-4c5e-bbe7-5e915eb2a720}')!

WAAcceptCharset comment: 'A WAAcceptCharset is a WAQualifiedValue with a value that is an instance of String. It represents how much a user agent prefers a certain character set for the response.'!

!WAAcceptCharset categoriesForClass!HTTP! !

!WAAcceptCharset class methodsFor!

valueClass	^ String! !

!WAAcceptCharset class categoriesForMethods!
valueClass!private! !
!

