"Filed out from Dolphin Smalltalk 7"!

WAQualifiedValue subclass: #WAAccept
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAccept guid: (GUID fromString: '{17004b12-8955-4bd9-b0d1-c07d81594040}')!
WAAccept comment: 'WAAccept class	instanceVariableNames: '''''!
!WAAccept categoriesForClass!Seaside-Core-HTTP! !
!WAAccept class methodsFor!

valueClass	^ WAMimeType! !
!WAAccept class categoriesFor: #valueClass!private! !

