"Filed out from Dolphin Smalltalk 7"!

WAQualifiedValue subclass: #WAAcceptEncoding
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAcceptEncoding guid: (GUID fromString: '{6bf32fc8-719b-439e-9f4d-f8dfb37e88fb}')!
WAAcceptEncoding comment: 'A WAAcceptCharset is a WAQualifiedValue with a value that is an instance of String. It represents how much a user agent prefers a certain encoding for the response.'!
!WAAcceptEncoding categoriesForClass!Seaside-Core-HTTP! !
!WAAcceptEncoding class methodsFor!

valueClass	^ String! !
!WAAcceptEncoding class categoriesFor: #valueClass!private! !

