"Filed out from Dolphin Smalltalk"!

WAQualifiedValue subclass: #WAAcceptCharset
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAcceptCharset guid: (GUID fromString: '{39276e4c-06e6-4b07-b0bc-9d3970269515}')!

WAAcceptCharset comment: 'A WAAcceptCharset is a WAQualifiedValue with a value that is an instance of String. It represents how much a user agent prefers a certain character set for the response.'!

!WAAcceptCharset categoriesForClass!Seaside-Core-HTTP! !

!WAAcceptCharset class methodsFor!

valueClass	^ String! !

!WAAcceptCharset class categoriesForMethods!
valueClass!private! !
!

