"Filed out from Dolphin Smalltalk 7"!

WAQualifiedValue subclass: #WAAcceptCharset
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAcceptCharset guid: (GUID fromString: '{6c30511a-4f3e-40ca-be65-ead705858224}')!
WAAcceptCharset comment: 'WAAcceptCharset class	instanceVariableNames: '''''!
!WAAcceptCharset categoriesForClass!Seaside-Core-HTTP! !
!WAAcceptCharset class methodsFor!

valueClass	^ String! !
!WAAcceptCharset class categoriesFor: #valueClass!private! !

