"Filed out from Dolphin Smalltalk 7"!

WAVisiblePresenterGuide subclass: #WAAllPresenterGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAllPresenterGuide guid: (GUID fromString: '{3e80bd3a-7eca-4857-99c6-426a4e353f84}')!
WAAllPresenterGuide comment: 'Visit the tree of all Presenters and their registered #children.'!
!WAAllPresenterGuide categoriesForClass!Seaside-Component-Visitors! !
!WAAllPresenterGuide methodsFor!

shouldVisitNextPresenterOf: aDecoration	^ true! !
!WAAllPresenterGuide categoriesFor: #shouldVisitNextPresenterOf:!private! !

