"Filed out from Dolphin Smalltalk"!

WAVisiblePresenterGuide subclass: #WAAllPresenterGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAllPresenterGuide guid: (GUID fromString: '{2e849f1b-a88c-4ea5-89c1-2c519e63d5a5}')!

WAAllPresenterGuide comment: 'Visit the tree of all Presenters and their registered #children.'!

!WAAllPresenterGuide categoriesForClass!Seaside-Component-Visitors! !

!WAAllPresenterGuide methodsFor!

shouldVisitNextPresenterOf: aDecoration	^ true! !

!WAAllPresenterGuide categoriesForMethods!
shouldVisitNextPresenterOf:!private! !
!

