"Filed out from Dolphin Smalltalk"!

WAVisiblePresenterGuide subclass: #WAAllPresenterGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAllPresenterGuide guid: (GUID fromString: '{84f9d922-dbb5-4fef-a6d4-b8d52429bd2a}')!

WAAllPresenterGuide comment: 'Visit the tree of all Presenters and their registered #children.'!

!WAAllPresenterGuide categoriesForClass!Visitors! !

!WAAllPresenterGuide methodsFor!

shouldVisitNextPresenterOf: aDecoration	^ true! !

!WAAllPresenterGuide categoriesForMethods!
shouldVisitNextPresenterOf:!private! !
!

