"Filed out from Dolphin Smalltalk"!

WAConfigurationElement subclass: #WAAttributeExpression
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAttributeExpression guid: (GUID fromString: '{690f5a73-d2cd-45e8-91ec-f424e3faafa7}')!

WAAttributeExpression comment: ''!

!WAAttributeExpression categoriesForClass!Configuration! !

!WAAttributeExpression methodsFor!

determineValueWithContext: aContext configuration: aConfiguration	self subclassResponsibility! !

!WAAttributeExpression categoriesForMethods!
determineValueWithContext:configuration:!public!values! !
!

