"Filed out from Dolphin Smalltalk"!

WAConfigurationElement subclass: #WAAttributeExpression
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAttributeExpression guid: (GUID fromString: '{227e08ea-d429-474a-9c14-f8f8c582a6d4}')!

WAAttributeExpression comment: ''!

!WAAttributeExpression categoriesForClass!Seaside-Core-Configuration! !

!WAAttributeExpression methodsFor!

determineValueWithContext: aContext configuration: aConfiguration	self subclassResponsibility! !

!WAAttributeExpression categoriesForMethods!
determineValueWithContext:configuration:!public!values! !
!

