"Filed out from Dolphin Smalltalk 7"!

WAConfigurationElement subclass: #WAAttributeExpression
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAAttributeExpression guid: (GUID fromString: '{f0f74fc7-5824-448c-ad04-9794029e2677}')!
WAAttributeExpression comment: ''!
!WAAttributeExpression categoriesForClass!Seaside-Core-Configuration! !
!WAAttributeExpression methodsFor!

determineValueWithContext: aContext configuration: aConfiguration	self subclassResponsibility! !
!WAAttributeExpression categoriesFor: #determineValueWithContext:configuration:!public!values! !

