"Filed out from Dolphin Smalltalk"!

WAMediaElementTag subclass: #WAAudioTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAAudioTag guid: (GUID fromString: '{878ee3bb-1c64-4dd2-9edb-e711fe2de57c}')!

WAAudioTag comment: 'no known browser support, might require an open codec like Ogg Vorbis, might first appear in Opera and MozillaAn audio element represents a sound or audio stream.Content may be provided inside the audio element so that older Web browsers, which do not support audio, can display text to the user informing them of how to access the audio contents. User agents should not show this fallback content to the user. '!

!WAAudioTag categoriesForClass!Seaside-Canvas-Tags! !

!WAAudioTag methodsFor!

tag	^ 'audio'! !

!WAAudioTag categoriesForMethods!
tag!accessing!public! !
!

