"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WACancelActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WACancelActionCallback guid: (GUID fromString: '{ad4861c6-ee5f-4158-addb-1e2a862d8b96}')!
WACancelActionCallback comment: ''!
!WACancelActionCallback categoriesForClass!Seaside-Core-Callbacks! !
!WACancelActionCallback methodsFor!

priority	^ -5! !
!WACancelActionCallback categoriesFor: #priority!accessing!public! !

