"Filed out from Dolphin Smalltalk 7"!

WASubmitButtonTag subclass: #WACancelButtonTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WACancelButtonTag guid: (GUID fromString: '{9274d9f1-4319-4cc0-81de-849c4569b02c}')!
WACancelButtonTag comment: ''!
!WACancelButtonTag categoriesForClass!Seaside-Canvas-Tags! !
!WACancelButtonTag methodsFor!

callback: aBlock	self name: (self storeCallback: (WACancelActionCallback on: aBlock))! !
!WACancelButtonTag categoriesFor: #callback:!callbacks!public! !

