"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WACancelActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WACancelActionCallback guid: (GUID fromString: '{991bc56a-255d-41a4-ac61-f268ddc51036}')!
WACancelActionCallback comment: ''!
!WACancelActionCallback categoriesForClass!Seaside-Core-Callbacks! !
!WACancelActionCallback methodsFor!

priority	^ -5! !
!WACancelActionCallback categoriesFor: #priority!accessing!public! !

