"Filed out from Dolphin Smalltalk"!

WAComponent subclass: #WACanvasTestComponent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACanvasTestComponent guid: (GUID fromString: '{5ced54e6-1e9e-46b3-af74-a3c689e5764e}')!

WACanvasTestComponent comment: ''!

!WACanvasTestComponent categoriesForClass!Seaside-Tests-RenderLoop! !

!WACanvasTestComponent methodsFor!

renderContentOn: html 	html paragraph: 'I should be decorated.'! !

!WACanvasTestComponent categoriesForMethods!
renderContentOn:!public!rendering! !
!

