"Filed out from Dolphin Smalltalk"!

WAComponent subclass: #WACanvasTestComponent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACanvasTestComponent guid: (GUID fromString: '{aeb8cfa1-8c5f-4f5f-83d7-d8490ef330b4}')!

WACanvasTestComponent comment: ''!

!WACanvasTestComponent categoriesForClass!Unclassified! !

!WACanvasTestComponent methodsFor!

renderContentOn: html 	html paragraph: 'I should be decorated.'! !

!WACanvasTestComponent categoriesForMethods!
renderContentOn:!public!rendering! !
!

