"Filed out from Dolphin Smalltalk"!

WAActionCallback subclass: #WACancelActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACancelActionCallback guid: (GUID fromString: '{d10f938d-b65e-4616-b3db-ac50472f0cfe}')!

WACancelActionCallback comment: ''!

!WACancelActionCallback categoriesForClass!Callbacks! !

!WACancelActionCallback methodsFor!

priority	^ -5! !

!WACancelActionCallback categoriesForMethods!
priority!accessing!public! !
!

