"Filed out from Dolphin Smalltalk"!

WACollectionAttributeEditor subclass: #WAClassBindingCollectionAttributeEditor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAClassBindingCollectionAttributeEditor guid: (GUID fromString: '{1b52d876-3f83-48c9-9b76-e1f35c1e03aa}')!

WAClassBindingCollectionAttributeEditor comment: ''!

!WAClassBindingCollectionAttributeEditor categoriesForClass!Seaside-Tools-Web! !

!WAClassBindingCollectionAttributeEditor methodsFor!

optionForValue: anObject	^ anObject value!

valueForOption: anObject	^ GRPlatform current bindingOf: anObject! !

!WAClassBindingCollectionAttributeEditor categoriesForMethods!
optionForValue:!private! !
valueForOption:!private! !
!

