"Filed out from Dolphin Smalltalk"!

WAAbstractTextAreaTag subclass: #WAColorInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAColorInputTag guid: (GUID fromString: '{a3052247-8571-4a9f-a290-dfb97717bd09}')!

WAColorInputTag comment: 'Provide a user interface element that lets a user specify a color'!

!WAColorInputTag categoriesForClass!Seaside-Canvas-Tags! !

!WAColorInputTag methodsFor!

type	^ 'color'! !

!WAColorInputTag categoriesForMethods!
type!accessing!public! !
!

