"Filed out from Dolphin Smalltalk 7"!

WAAbstractTextAreaTag subclass: #WAColorInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAColorInputTag guid: (GUID fromString: '{8e5d3f51-de98-4449-9ada-570c7448fd1d}')!
WAColorInputTag comment: ''!
!WAColorInputTag categoriesForClass!Seaside-Canvas-Tags! !
!WAColorInputTag methodsFor!

type	^ 'color'! !
!WAColorInputTag categoriesFor: #type!accessing!public! !

