"Filed out from Dolphin Smalltalk 7"!

WAAbstractTextAreaTag subclass: #WAColorInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAColorInputTag guid: (GUID fromString: '{e472a6b7-be41-4764-ba11-dc9900bdfd1e}')!
WAColorInputTag comment: 'Provide a user interface element that lets a user specify a color'!
!WAColorInputTag categoriesForClass!Seaside-Canvas-Tags! !
!WAColorInputTag methodsFor!

type	^ 'color'! !
!WAColorInputTag categoriesFor: #type!accessing!public! !

