"Filed out from Dolphin Smalltalk"!

WADynamicVariable subclass: #WACurrentCallbackProcessingActionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACurrentCallbackProcessingActionContinuation guid: (GUID fromString: '{d3f1bf07-c054-4685-9aa0-14db759d48f6}')!

WACurrentCallbackProcessingActionContinuation comment: ''!

!WACurrentCallbackProcessingActionContinuation categoriesForClass!Base! !

