"Filed out from Dolphin Smalltalk"!

WADynamicVariable subclass: #WACurrentExceptionHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACurrentExceptionHandler guid: (GUID fromString: '{8cff56d7-758d-4494-8a30-51e9dfcc1eaf}')!

WACurrentExceptionHandler comment: 'I hold a reference to the current WAExceptionHandler. This may be needed when nesting exception handlers so that the look up of an exception handler from within an exception handler block still succeeds.'!

!WACurrentExceptionHandler categoriesForClass!Seaside-Core-Filter! !

