"Filed out from Dolphin Smalltalk"!

WADynamicVariable subclass: #WACurrentCallbackProcessingActionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WACurrentCallbackProcessingActionContinuation guid: (GUID fromString: '{05230e95-3a2b-4050-bc9a-5a67251bb720}')!

WACurrentCallbackProcessingActionContinuation comment: ''!

!WACurrentCallbackProcessingActionContinuation categoriesForClass!Seaside-RenderLoop-Base! !

