"Filed out from Dolphin Smalltalk 7"!

WADynamicVariable subclass: #WACurrentCallbackProcessingActionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WACurrentCallbackProcessingActionContinuation guid: (GUID fromString: '{69aa80eb-8b26-4660-b638-1dd157d4ae41}')!
WACurrentCallbackProcessingActionContinuation comment: ''!
!WACurrentCallbackProcessingActionContinuation categoriesForClass!Seaside-RenderLoop! !
