"Filed out from Dolphin Smalltalk 7"!

WADynamicVariable subclass: #WACurrentRequestContext
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WACurrentRequestContext guid: (GUID fromString: '{992c1797-fc67-4086-aaa3-3209bbee2731}')!
WACurrentRequestContext comment: 'WACurrentRequestContext class	instanceVariableNames: '''''!
!WACurrentRequestContext categoriesForClass!Seaside-Core-RequestHandling! !
!WACurrentRequestContext class methodsFor!

defaultValue	^ WARequestContextNotFound signal! !
!WACurrentRequestContext class categoriesFor: #defaultValue!defaults!public! !

