"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WADefaultActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WADefaultActionCallback guid: (GUID fromString: '{7b1b776d-e977-440e-8973-5fc89a4eb0fd}')!
WADefaultActionCallback comment: ''!
!WADefaultActionCallback categoriesForClass!Seaside-Core-Callbacks! !
!WADefaultActionCallback methodsFor!

priority	^ 10! !
!WADefaultActionCallback categoriesFor: #priority!accessing!public! !

