"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WADefaultActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WADefaultActionCallback guid: (GUID fromString: '{3be7ead1-8c0a-4ddf-829b-6d9cf03d3d86}')!
WADefaultActionCallback comment: ''!
!WADefaultActionCallback categoriesForClass!Seaside-Core-Callbacks! !
!WADefaultActionCallback methodsFor!

priority	^ 10! !
!WADefaultActionCallback categoriesFor: #priority!accessing!public! !

