"Filed out from Dolphin Smalltalk"!

WAActionCallback subclass: #WADefaultActionCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADefaultActionCallback guid: (GUID fromString: '{a7879a2b-5243-4266-8652-a0ff27199266}')!

WADefaultActionCallback comment: ''!

!WADefaultActionCallback categoriesForClass!Seaside-Core-Callbacks! !

!WADefaultActionCallback methodsFor!

priority	^ 10! !

!WADefaultActionCallback categoriesForMethods!
priority!accessing!public! !
!

