"Filed out from Dolphin Smalltalk 7"!

WADispatcherSubPage subclass: #WADispatcherEmptyPage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WADispatcherEmptyPage guid: (GUID fromString: '{371d2944-6664-40ee-a234-2ea10139465e}')!
WADispatcherEmptyPage comment: ''!
!WADispatcherEmptyPage categoriesForClass!Seaside-Tools-Web! !
!WADispatcherEmptyPage class methodsFor!

on: parentComponent	^ self new		parent: parentComponent;		yourself! !
!WADispatcherEmptyPage class categoriesFor: #on:!instance creation!public! !

