"Filed out from Dolphin Smalltalk"!

WADispatcherSubPage subclass: #WADispatcherEmptyPage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADispatcherEmptyPage guid: (GUID fromString: '{ec0a84b8-e8eb-4da0-a96f-76d4bde7c9d1}')!

WADispatcherEmptyPage comment: ''!

!WADispatcherEmptyPage categoriesForClass!Unclassified! !

!WADispatcherEmptyPage class methodsFor!

on: parentComponent	^ self new		parent: parentComponent;		yourself! !

!WADispatcherEmptyPage class categoriesForMethods!
on:!instance creation!public! !
!

