"Filed out from Dolphin Smalltalk"!

WAComponent subclass: #WADispatcherSubPage
	instanceVariableNames: 'parent'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADispatcherSubPage guid: (GUID fromString: '{55f91683-1966-47ce-96aa-4d4781bec524}')!

WADispatcherSubPage comment: ''!

!WADispatcherSubPage categoriesForClass!Seaside-Tools-Web! !

!WADispatcherSubPage methodsFor!

parent	^ parent!

parent: anObject	parent := anObject! !

!WADispatcherSubPage categoriesForMethods!
parent!accessing!public! !
parent:!accessing!public! !
!

