"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #WADispatcherSubPage
	instanceVariableNames: 'parent'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WADispatcherSubPage guid: (GUID fromString: '{6c9b9942-fdc0-4c8f-8e4d-6b21e7b020c0}')!
WADispatcherSubPage comment: ''!
!WADispatcherSubPage categoriesForClass!Seaside-Tools-Web! !
!WADispatcherSubPage methodsFor!

parent	^ parent!

parent: anObject	parent := anObject! !
!WADispatcherSubPage categoriesFor: #parent!accessing!public! !
!WADispatcherSubPage categoriesFor: #parent:!accessing!public! !

