"Filed out from Dolphin Smalltalk"!

WAComponent subclass: #WADispatcherSubPage
	instanceVariableNames: 'parent'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADispatcherSubPage guid: (GUID fromString: '{43a491de-6f65-41ba-87ce-1be21e35db3b}')!

WADispatcherSubPage comment: ''!

!WADispatcherSubPage categoriesForClass!Unclassified! !

!WADispatcherSubPage methodsFor!

parent	^ parent!

parent: anObject	parent := anObject! !

!WADispatcherSubPage categoriesForMethods!
parent!accessing!public! !
parent:!accessing!public! !
!

