"Filed out from Dolphin Smalltalk"!

WADispatcherSubPage subclass: #WADispatcherEmptyPage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADispatcherEmptyPage guid: (GUID fromString: '{f8734c9b-c285-440e-ac0b-b530284b99c6}')!

WADispatcherEmptyPage comment: ''!

!WADispatcherEmptyPage categoriesForClass!Seaside-Tools-Web! !

!WADispatcherEmptyPage class methodsFor!

on: parentComponent	^ self new		parent: parentComponent;		yourself! !

!WADispatcherEmptyPage class categoriesForMethods!
on:!instance creation!public! !
!

