"Filed out from Dolphin Smalltalk"!

GRDynamicVariable subclass: #WADynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADynamicVariable guid: (GUID fromString: '{2dfa25d3-b76a-4e7f-98b1-1f0c4259a812}')!

WADynamicVariable comment: 'I exist for legacy purposes. You should subclass GRDynamicVariable.'!

!WADynamicVariable categoriesForClass!Seaside-Core-Utilities! !

