"Filed out from Dolphin Smalltalk"!

GRDynamicVariable subclass: #WADynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WADynamicVariable guid: (GUID fromString: '{42e95099-b73a-4694-9c76-db4b8f0b15bb}')!

WADynamicVariable comment: 'I exist for legacy purposes. You should subclass GRDynamicVariable.'!

!WADynamicVariable categoriesForClass!Utilities! !

