"Filed out from Dolphin Smalltalk"!

WATask subclass: #WAEmptyTestTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAEmptyTestTask guid: (GUID fromString: '{d815cddd-5a52-46ec-9d24-50708f4060a2}')!

WAEmptyTestTask comment: ''!

!WAEmptyTestTask categoriesForClass!Seaside-Tests-Functional! !

!WAEmptyTestTask methodsFor!

go	"do nothing. I wonder what happens?"! !

!WAEmptyTestTask categoriesForMethods!
go!public!running! !
!

