"Filed out from Dolphin Smalltalk 7"!

WATask subclass: #WAEmptyTestTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAEmptyTestTask guid: (GUID fromString: '{5a8975ae-61b0-498a-bf36-0110911d2f5e}')!
WAEmptyTestTask comment: ''!
!WAEmptyTestTask categoriesForClass!Seaside-Tests-Functional! !
!WAEmptyTestTask methodsFor!

go	"do nothing. I wonder what happens?"! !
!WAEmptyTestTask categoriesFor: #go!public!running! !

