"Filed out from Dolphin Smalltalk 7"!

WATask subclass: #WAEmptyTestTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAEmptyTestTask guid: (GUID fromString: '{0460cfdf-bc57-4122-b582-d49f47d48982}')!
WAEmptyTestTask comment: ''!
!WAEmptyTestTask categoriesForClass!Seaside-Tests-Functional! !
!WAEmptyTestTask methodsFor!

go	"do nothing. I wonder what happens?"! !
!WAEmptyTestTask categoriesFor: #go!public!running! !

