"Filed out from Dolphin Smalltalk"!

GRError subclass: #WAError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAError guid: (GUID fromString: '{fb5cd4ac-3387-4ef5-9df6-823dfc50ab2c}')!

WAError comment: 'Common superclass for Seaside errors'!

!WAError categoriesForClass!Exceptions! !

!WAError class methodsFor!

isAbstract 	^ self == WAError! !

!WAError class categoriesForMethods!
isAbstract!public!testing! !
!

