"Filed out from Dolphin Smalltalk"!

GRError subclass: #WAError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAError guid: (GUID fromString: '{fa963798-4569-41ce-b95e-6360f2f2abf2}')!

WAError comment: 'Common superclass for Seaside errors'!

!WAError categoriesForClass!Seaside-Core-Exceptions! !

!WAError class methodsFor!

isAbstract 	^ self == WAError! !

!WAError class categoriesForMethods!
isAbstract!public!testing! !
!

