"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #WAExampleComponent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAExampleComponent guid: (GUID fromString: '{48908d80-f345-4257-afda-1b7053dcc782}')!
WAExampleComponent comment: ''!
!WAExampleComponent categoriesForClass!Seaside-Examples-Misc! !
!WAExampleComponent methodsFor!

rendererClass	^ WAHtmlCanvas! !
!WAExampleComponent categoriesFor: #rendererClass!public!rendering! !

!WAExampleComponent class methodsFor!

canBeRoot	^ true! !
!WAExampleComponent class categoriesFor: #canBeRoot!public!testing! !

