"Filed out from Dolphin Smalltalk 7"!

WADelegationTask subclass: #WAFlowDelegationTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAFlowDelegationTask guid: (GUID fromString: '{2e62b7d8-6b80-4ae3-a7ef-47f59e4b44f5}')!
WAFlowDelegationTask comment: ''!
!WAFlowDelegationTask categoriesForClass!Seaside-Tests-Flow-Functional! !
!WAFlowDelegationTask methodsFor!

go	self call: component1.	self call: component2! !
!WAFlowDelegationTask categoriesFor: #go!public!running! !

