"Filed out from Dolphin Smalltalk"!

WADelegationTask subclass: #WAFlowDelegationTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAFlowDelegationTask guid: (GUID fromString: '{84b69024-3661-440b-a362-f82b0961b44f}')!

WAFlowDelegationTask comment: ''!

!WAFlowDelegationTask categoriesForClass!Functional! !

!WAFlowDelegationTask methodsFor!

go	self call: component1.	self call: component2! !

!WAFlowDelegationTask categoriesForMethods!
go!public!running! !
!

