"Filed out from Dolphin Smalltalk"!

WADelegationTask subclass: #WAFlowDelegationTask
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAFlowDelegationTask guid: (GUID fromString: '{00ef33c5-715d-4fae-845a-81fc48b4391b}')!

WAFlowDelegationTask comment: ''!

!WAFlowDelegationTask categoriesForClass!Seaside-Tests-Flow-Functional! !

!WAFlowDelegationTask methodsFor!

go	self call: component1.	self call: component2! !

!WAFlowDelegationTask categoriesForMethods!
go!public!running! !
!

