"Filed out from Dolphin Smalltalk 7"!

WARenderPhaseContinuation subclass: #WAFlushingRenderPhaseContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAFlushingRenderPhaseContinuation guid: (GUID fromString: '{a52bc1e3-38ec-446b-a71f-023744d7fdf3}')!
WAFlushingRenderPhaseContinuation comment: ''!
!WAFlushingRenderPhaseContinuation categoriesForClass!Seaside-RenderLoop! !
!WAFlushingRenderPhaseContinuation methodsFor!

documentOpened: aResponse	aResponse flush! !
!WAFlushingRenderPhaseContinuation categoriesFor: #documentOpened:!processing!public! !

