"Filed out from Dolphin Smalltalk"!

WAFileHandlerListing subclass: #WAForbiddenFileHandlerListing
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAForbiddenFileHandlerListing guid: (GUID fromString: '{55e03c3d-9ac6-462d-8b9c-a05e600595ea}')!

WAForbiddenFileHandlerListing comment: ''!

!WAForbiddenFileHandlerListing categoriesForClass!Libraries! !

!WAForbiddenFileHandlerListing methodsFor!

responseForLibraries	context responseGenerator		forbidden;		respond!

responseForLibrary: aLibrary 	context responseGenerator		forbidden;		respond! !

!WAForbiddenFileHandlerListing categoriesForMethods!
responseForLibraries!public!responding! !
responseForLibrary:!public!responding! !
!

