"Filed out from Dolphin Smalltalk"!

WAFileHandlerListing subclass: #WAForbiddenFileHandlerListing
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAForbiddenFileHandlerListing guid: (GUID fromString: '{2da3c96a-88a8-49b8-a433-577b305e4820}')!

WAForbiddenFileHandlerListing comment: ''!

!WAForbiddenFileHandlerListing categoriesForClass!Seaside-Core-Libraries! !

!WAForbiddenFileHandlerListing methodsFor!

responseForLibraries	context responseGenerator		forbidden;		respond!

responseForLibrary: aLibrary 	context responseGenerator		forbidden;		respond! !

!WAForbiddenFileHandlerListing categoriesForMethods!
responseForLibraries!public!responding! !
responseForLibrary:!public!responding! !
!

