"Filed out from Dolphin Smalltalk 7"!

WATask subclass: #WAFunctionalTaskTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAFunctionalTaskTest guid: (GUID fromString: '{5471b58f-2042-4b1b-a7a3-d164fcb1144b}')!
WAFunctionalTaskTest comment: ''!
!WAFunctionalTaskTest categoriesForClass!Seaside-Tests-Functional! !
!WAFunctionalTaskTest class methodsFor!

isFunctionalTest	^ self name ~= #WAFunctionalTaskTest! !
!WAFunctionalTaskTest class categoriesFor: #isFunctionalTest!public!testing! !

