"Filed out from Dolphin Smalltalk"!

WATask subclass: #WAFunctionalTaskTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAFunctionalTaskTest guid: (GUID fromString: '{b1ff9ab0-49b7-459a-bf33-01f505f6db80}')!

WAFunctionalTaskTest comment: ''!

!WAFunctionalTaskTest categoriesForClass!Seaside-Tests-Functional! !

!WAFunctionalTaskTest class methodsFor!

isFunctionalTest	^ self name ~= #WAFunctionalTaskTest! !

!WAFunctionalTaskTest class categoriesForMethods!
isFunctionalTest!public!testing! !
!

