"Filed out from Dolphin Smalltalk 7"!

WATask subclass: #WAFunctionalTaskTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAFunctionalTaskTest guid: (GUID fromString: '{f250b45b-3f01-42ad-a4f9-78d22b54d30b}')!
WAFunctionalTaskTest comment: ''!
!WAFunctionalTaskTest categoriesForClass!Seaside-Tests-Functional! !
!WAFunctionalTaskTest class methodsFor!

isFunctionalTest	^ self name ~= #WAFunctionalTaskTest! !
!WAFunctionalTaskTest class categoriesFor: #isFunctionalTest!public!testing! !

