"Filed out from Dolphin Smalltalk"!

WATagBrush subclass: #WAHorizontalRuleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAHorizontalRuleTag guid: (GUID fromString: '{91756427-d692-430f-a455-99c8307861f7}')!

WAHorizontalRuleTag comment: 'The HR element causes a horizontal rule to be rendered by visual user agents.The amount of vertical space inserted between a rule and the content that surrounds it depends on the user agent.'!

!WAHorizontalRuleTag categoriesForClass!Seaside-Canvas-Tags! !

!WAHorizontalRuleTag methodsFor!

isClosed	^ true!

tag	^ 'hr'! !

!WAHorizontalRuleTag categoriesForMethods!
isClosed!public!testing! !
tag!accessing!public! !
!

