"Filed out from Dolphin Smalltalk"!

WATagBrush subclass: #WAHorizontalRuleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAHorizontalRuleTag guid: (GUID fromString: '{358b2034-6810-4df9-a327-4d6f835c77d5}')!

WAHorizontalRuleTag comment: 'The HR element causes a horizontal rule to be rendered by visual user agents.The amount of vertical space inserted between a rule and the content that surrounds it depends on the user agent.'!

!WAHorizontalRuleTag categoriesForClass!Tags! !

!WAHorizontalRuleTag methodsFor!

isClosed	^ true!

tag	^ 'hr'! !

!WAHorizontalRuleTag categoriesForMethods!
isClosed!public!testing! !
tag!accessing!public! !
!

