"Filed out from Dolphin Smalltalk 7"!

WATagBrush subclass: #WAHorizontalRuleTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAHorizontalRuleTag guid: (GUID fromString: '{9bf05859-210b-4d1b-ab14-e531dd7626ec}')!
WAHorizontalRuleTag comment: 'The HR element causes a horizontal rule to be rendered by visual user agents.The amount of vertical space inserted between a rule and the content that surrounds it depends on the user agent.'!
!WAHorizontalRuleTag categoriesForClass!Seaside-Canvas-Tags! !
!WAHorizontalRuleTag methodsFor!

isClosed	^ true!

tag	^ 'hr'! !
!WAHorizontalRuleTag categoriesFor: #isClosed!public!testing! !
!WAHorizontalRuleTag categoriesFor: #tag!accessing!public! !

