"Filed out from Dolphin Smalltalk"!

WAFileHandlerListingTest subclass: #WAHtmlFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAHtmlFileHandlerListingTest guid: (GUID fromString: '{ee990d61-d2b4-4204-a62f-58bffafaf453}')!

WAHtmlFileHandlerListingTest comment: ''!

!WAHtmlFileHandlerListingTest categoriesForClass!Seaside-Tests-Environment-Base! !

!WAHtmlFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textHtml!

handlerClass	^ WAHtmlFileHandlerListing! !

!WAHtmlFileHandlerListingTest categoriesForMethods!
expectedMimeType!public!testing! !
handlerClass!public!testing! !
!

