"Filed out from Dolphin Smalltalk 7"!

WAFileHandlerListingTest subclass: #WAHtmlFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAHtmlFileHandlerListingTest guid: (GUID fromString: '{f35cfa9e-754e-4374-8b39-65d265123e24}')!
WAHtmlFileHandlerListingTest comment: ''!
!WAHtmlFileHandlerListingTest categoriesForClass!Seaside-Tests-Environment! !
!WAHtmlFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textHtml!

handlerClass	^ WAHtmlFileHandlerListing! !
!WAHtmlFileHandlerListingTest categoriesFor: #expectedMimeType!public!testing! !
!WAHtmlFileHandlerListingTest categoriesFor: #handlerClass!public!testing! !

