"Filed out from Dolphin Smalltalk"!

WAFileHandlerListingTest subclass: #WAHtmlFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAHtmlFileHandlerListingTest guid: (GUID fromString: '{096b3f09-3f3a-402a-8ee3-f173e22e6316}')!

WAHtmlFileHandlerListingTest comment: ''!

!WAHtmlFileHandlerListingTest categoriesForClass!Base! !

!WAHtmlFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textHtml!

handlerClass	^ WAHtmlFileHandlerListing! !

!WAHtmlFileHandlerListingTest categoriesForMethods!
expectedMimeType!public!testing! !
handlerClass!public!testing! !
!

