"Filed out from Dolphin Smalltalk"!

WAActionCallback subclass: #WAImageCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAImageCallback guid: (GUID fromString: '{fb7c9806-7c8f-4a2c-9f9d-f2f7fe1661bb}')!

WAImageCallback comment: ''!

!WAImageCallback categoriesForClass!Seaside-Core-Callbacks! !

!WAImageCallback methodsFor!

convertKey: aString	^ aString , '.x'! !

!WAImageCallback categoriesForMethods!
convertKey:!converting!public! !
!

