"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WAImageCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAImageCallback guid: (GUID fromString: '{c789ca1f-4949-4f28-9a20-20417570b804}')!
WAImageCallback comment: ''!
!WAImageCallback categoriesForClass!Seaside-Core-Callbacks! !
!WAImageCallback methodsFor!

convertKey: aString	^ aString , '.x'! !
!WAImageCallback categoriesFor: #convertKey:!converting!public! !

