"Filed out from Dolphin Smalltalk 7"!

WAActionCallback subclass: #WAImageCallback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAImageCallback guid: (GUID fromString: '{1ae9ef40-ef20-4138-be31-4594aa90a076}')!
WAImageCallback comment: ''!
!WAImageCallback categoriesForClass!Seaside-Core-Callbacks! !
!WAImageCallback methodsFor!

convertKey: aString	^ aString , '.x'! !
!WAImageCallback categoriesFor: #convertKey:!converting!public! !

