"Filed out from Dolphin Smalltalk"!

WAJsonBrush subclass: #WAJsonArrayBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAJsonArrayBrush guid: (GUID fromString: '{ae60cd26-d1d4-4ce9-8657-81335b7dfc58}')!

WAJsonArrayBrush comment: 'Brush for a JSON array'!

!WAJsonArrayBrush categoriesForClass!Seaside-JSON-Core-Brushes! !

!WAJsonArrayBrush methodsFor!

closeBrush	self document closeArray!

openBrush	self document openArray! !

!WAJsonArrayBrush categoriesForMethods!
closeBrush!private! !
openBrush!private! !
!

