"Filed out from Dolphin Smalltalk 7"!

WAJsonBrush subclass: #WAJsonElementBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonElementBrush guid: (GUID fromString: '{a2abea80-f90a-4272-85ef-5a09930e4cad}')!
WAJsonElementBrush comment: ''!
!WAJsonElementBrush categoriesForClass!Seaside-JSON-Core! !
!WAJsonElementBrush methodsFor!

closeBrush!

openBrush	canvas writeIfNotFirst: ', '! !
!WAJsonElementBrush categoriesFor: #closeBrush!private! !
!WAJsonElementBrush categoriesFor: #openBrush!private! !

