"Filed out from Dolphin Smalltalk 7"!

WAJsonBrush subclass: #WAJsonArrayBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonArrayBrush guid: (GUID fromString: '{9770a7ab-686f-4d2d-ae41-965d82fd0354}')!
WAJsonArrayBrush comment: ''!
!WAJsonArrayBrush categoriesForClass!Seaside-JSON-Core! !
!WAJsonArrayBrush methodsFor!

closeBrush	self document closeArray!

openBrush	self document openArray! !
!WAJsonArrayBrush categoriesFor: #closeBrush!private! !
!WAJsonArrayBrush categoriesFor: #openBrush!private! !

