"Filed out from Dolphin Smalltalk 7"!

WAError subclass: #WAJsonSyntaxError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonSyntaxError guid: (GUID fromString: '{7acc45f4-c635-4e75-a146-0c95b95a18e8}')!
WAJsonSyntaxError comment: '''From Pharo8.0.0 of 22 January 2020 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)] on 22 April 2020 at 9:01:54.416372 am'''!
!WAJsonSyntaxError categoriesForClass!Seaside-JSON-Core! !
