"Filed out from Dolphin Smalltalk 7"!

WAJsonBrush subclass: #WAJsonElementBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonElementBrush guid: (GUID fromString: '{ae395af6-771e-4352-ab08-3604576d8207}')!
WAJsonElementBrush comment: ''!
!WAJsonElementBrush categoriesForClass!Seaside-JSON-Core! !
!WAJsonElementBrush methodsFor!

closeBrush!

openBrush	canvas writeIfNotFirst: ', '! !
!WAJsonElementBrush categoriesFor: #closeBrush!private! !
!WAJsonElementBrush categoriesFor: #openBrush!private! !

