"Filed out from Dolphin Smalltalk 7"!

WAError subclass: #WAJsonSyntaxError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonSyntaxError guid: (GUID fromString: '{44fb6df4-4b7a-4f0c-910f-ebb10473b763}')!
WAJsonSyntaxError comment: 'A WAJsonSyntaxError signals invalid JSON input.'!
!WAJsonSyntaxError categoriesForClass!Seaside-JSON-Core! !
