"Filed out from Dolphin Smalltalk 7"!

WAJsonBrush subclass: #WAJsonArrayBrush
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAJsonArrayBrush guid: (GUID fromString: '{a7432a00-76d9-4ca0-a7de-0a890b3b7fb8}')!
WAJsonArrayBrush comment: ''!
!WAJsonArrayBrush categoriesForClass!Seaside-JSON-Core! !
!WAJsonArrayBrush methodsFor!

closeBrush	self document closeArray!

openBrush	self document openArray! !
!WAJsonArrayBrush categoriesFor: #closeBrush!private! !
!WAJsonArrayBrush categoriesFor: #openBrush!private! !

