"Filed out from Dolphin Smalltalk"!

WAError subclass: #WAJsonSyntaxError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAJsonSyntaxError guid: (GUID fromString: '{cada564c-3ee0-4c88-be36-99cdfff7becf}')!

WAJsonSyntaxError comment: 'A WAJsonSyntaxError signals invalid JSON input.'!

!WAJsonSyntaxError categoriesForClass!Base! !

