"Filed out from Dolphin Smalltalk 7"!

WAError subclass: #WAMaximumNumberOfSessionsExceededError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAMaximumNumberOfSessionsExceededError guid: (GUID fromString: '{2d54ef49-1b55-4d06-beab-31574f3bc049}')!
WAMaximumNumberOfSessionsExceededError comment: 'WACache subclass: #WAMutualExclusionCache	instanceVariableNames: ''mutex cache''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Seaside-Core-Cache'''!
!WAMaximumNumberOfSessionsExceededError categoriesForClass!Seaside-Core-Cache! !
