"Filed out from Dolphin Smalltalk"!

WAError subclass: #WAMaximumNumberOfSessionsExceededError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAMaximumNumberOfSessionsExceededError guid: (GUID fromString: '{453bd510-cf7a-41c4-9bdf-c5b6f13c27ab}')!

WAMaximumNumberOfSessionsExceededError comment: 'I signal that the maximum number of enties in a WAHashCache has been exceeded. If you use the overflow strategy #signalError you''re supposed to handle me and display an error message. A filter is ideal for this.http://ora-00018.ora-code.com/'!

!WAMaximumNumberOfSessionsExceededError categoriesForClass!Cache! !

