"Filed out from Dolphin Smalltalk 7"!

WAError subclass: #WAMaximumNumberOfSessionsExceededError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAMaximumNumberOfSessionsExceededError guid: (GUID fromString: '{23d90e00-08ae-4a37-a190-166441c6e713}')!
WAMaximumNumberOfSessionsExceededError comment: 'http://ora-00018.ora-code.com/'!
!WAMaximumNumberOfSessionsExceededError categoriesForClass!Seaside-Core-Cache! !
