"Filed out from Dolphin Smalltalk"!

GRNotification subclass: #WANotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WANotification guid: (GUID fromString: '{98842841-a8e5-4b5c-99bc-14fd148d49c5}')!

WANotification comment: 'Common superclass for Seaside notifications'!

!WANotification categoriesForClass!Exceptions! !

!WANotification class methodsFor!

isAbstract 	^ self == WANotification! !

!WANotification class categoriesForMethods!
isAbstract!public!testing! !
!

