"Filed out from Dolphin Smalltalk"!

GRNotification subclass: #WANotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WANotification guid: (GUID fromString: '{f17ca832-2748-4d84-a159-32dd5144b00e}')!

WANotification comment: 'Common superclass for Seaside notifications'!

!WANotification categoriesForClass!Seaside-Core-Exceptions! !

!WANotification class methodsFor!

isAbstract 	^ self == WANotification! !

!WANotification class categoriesForMethods!
isAbstract!public!testing! !
!

