"Filed out from Dolphin Smalltalk"!

WASessionContinuation subclass: #WANullSessionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WANullSessionContinuation guid: (GUID fromString: '{e7d66013-1a73-4642-b109-9a1b1e77c9fb}')!

WANullSessionContinuation comment: ''!

!WANullSessionContinuation categoriesForClass!Continuations! !

!WANullSessionContinuation methodsFor!

handleFiltered: aRequestContext	"Do nothing"! !

!WANullSessionContinuation categoriesForMethods!
handleFiltered:!handling!public! !
!

