"Filed out from Dolphin Smalltalk 7"!

WASessionContinuation subclass: #WANullSessionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WANullSessionContinuation guid: (GUID fromString: '{d2c330c6-8f2a-4f6e-9288-89bd5dad3674}')!
WANullSessionContinuation comment: ''!
!WANullSessionContinuation categoriesForClass!Seaside-Session! !
!WANullSessionContinuation methodsFor!

handleFiltered: aRequestContext	"Do nothing"! !
!WANullSessionContinuation categoriesFor: #handleFiltered:!handling!public! !

