"Filed out from Dolphin Smalltalk"!

WASessionContinuation subclass: #WANullSessionContinuation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WANullSessionContinuation guid: (GUID fromString: '{51c54f14-2d0d-4646-9c15-d02ee362b9eb}')!

WANullSessionContinuation comment: ''!

!WANullSessionContinuation categoriesForClass!Seaside-Session-Continuations! !

!WANullSessionContinuation methodsFor!

handleFiltered: aRequestContext	"Do nothing"! !

!WANullSessionContinuation categoriesForMethods!
handleFiltered:!handling!public! !
!

