"Filed out from Dolphin Smalltalk"!

WAObject subclass: #WAObjectUnderstandingUnregistered
	instanceVariableNames: 'hasReceivedUnregistered'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAObjectUnderstandingUnregistered guid: (GUID fromString: '{2d41d270-8b2d-4a39-b531-c5a026496f58}')!

WAObjectUnderstandingUnregistered comment: ''!

!WAObjectUnderstandingUnregistered categoriesForClass!Seaside-Tests-Core-Cache! !

!WAObjectUnderstandingUnregistered methodsFor!

hasReceivedUnregistered	^ hasReceivedUnregistered!

initialize	super initialize.	hasReceivedUnregistered := false!

unregistered	hasReceivedUnregistered := true! !

!WAObjectUnderstandingUnregistered categoriesForMethods!
hasReceivedUnregistered!accessing!public! !
initialize!initialization!public! !
unregistered!public!registration! !
!

