"Filed out from Dolphin Smalltalk"!

WAObject subclass: #WAObjectUnderstandingUnregistered
	instanceVariableNames: 'hasReceivedUnregistered'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAObjectUnderstandingUnregistered guid: (GUID fromString: '{f46a9be7-382b-41a5-a5a0-468b27869c98}')!

WAObjectUnderstandingUnregistered comment: ''!

!WAObjectUnderstandingUnregistered categoriesForClass!Cache! !

!WAObjectUnderstandingUnregistered methodsFor!

hasReceivedUnregistered	^ hasReceivedUnregistered!

initialize	super initialize.	hasReceivedUnregistered := false!

unregistered	hasReceivedUnregistered := true! !

!WAObjectUnderstandingUnregistered categoriesForMethods!
hasReceivedUnregistered!accessing!public! !
initialize!initialization!public! !
unregistered!public!registration! !
!

