"Filed out from Dolphin Smalltalk 7"!

WATagBrush subclass: #WAOptionalBreakTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAOptionalBreakTag guid: (GUID fromString: '{6911dc5d-73b0-4f65-a6a6-34019a788cf3}')!
WAOptionalBreakTag comment: ''!
!WAOptionalBreakTag categoriesForClass!Seaside-Canvas-Tags! !
!WAOptionalBreakTag methodsFor!

isClosed	^ true!

tag	^ 'wbr'! !
!WAOptionalBreakTag categoriesFor: #isClosed!public!testing! !
!WAOptionalBreakTag categoriesFor: #tag!accessing!public! !

