"Filed out from Dolphin Smalltalk"!

WATagBrush subclass: #WAOptionalBreakTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAOptionalBreakTag guid: (GUID fromString: '{4a97ab92-aa42-445f-9634-a063a617fe3d}')!

WAOptionalBreakTag comment: 'The <wbr> (Word Break Opportunity) tag specifies where in a text it would be ok to add a line-break.'!

!WAOptionalBreakTag categoriesForClass!Seaside-Canvas-Tags! !

!WAOptionalBreakTag methodsFor!

isClosed	^ true!

tag	^ 'wbr'! !

!WAOptionalBreakTag categoriesForMethods!
isClosed!public!testing! !
tag!accessing!public! !
!

