"Filed out from Dolphin Smalltalk"!

WATagBrush subclass: #WAOptionalBreakTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAOptionalBreakTag guid: (GUID fromString: '{23f12eed-decb-4a95-bdf9-107b7e7280e6}')!

WAOptionalBreakTag comment: 'The <wbr> (Word Break Opportunity) tag specifies where in a text it would be ok to add a line-break.'!

!WAOptionalBreakTag categoriesForClass!Tags! !

!WAOptionalBreakTag methodsFor!

isClosed	^ true!

tag	^ 'wbr'! !

!WAOptionalBreakTag categoriesForMethods!
isClosed!public!testing! !
tag!accessing!public! !
!

