"Filed out from Dolphin Smalltalk"!

WATextInputTag subclass: #WAPasswordInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAPasswordInputTag guid: (GUID fromString: '{73160a82-84dd-4fb8-9bc4-e5b4ce677f5f}')!

WAPasswordInputTag comment: 'I am a password input widget that does not display the entered text.'!

!WAPasswordInputTag categoriesForClass!Tags! !

!WAPasswordInputTag methodsFor!

type	^ 'password'! !

!WAPasswordInputTag categoriesForMethods!
type!accessing!public! !
!

