"Filed out from Dolphin Smalltalk"!

WATextInputTag subclass: #WAPasswordInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAPasswordInputTag guid: (GUID fromString: '{8fd12bcc-8e2a-4caf-a9b5-afe3ce917643}')!

WAPasswordInputTag comment: 'I am a password input widget that does not display the entered text.'!

!WAPasswordInputTag categoriesForClass!Seaside-Canvas-Tags! !

!WAPasswordInputTag methodsFor!

type	^ 'password'! !

!WAPasswordInputTag categoriesForMethods!
type!accessing!public! !
!

