"Filed out from Dolphin Smalltalk 7"!

WATextInputTag subclass: #WAPasswordInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAPasswordInputTag guid: (GUID fromString: '{3d586f8c-ce75-4e2a-932e-06ef331ebb80}')!
WAPasswordInputTag comment: 'I am a password input widget that does not display the entered text.'!
!WAPasswordInputTag categoriesForClass!Seaside-Canvas-Tags! !
!WAPasswordInputTag methodsFor!

type	^ 'password'! !
!WAPasswordInputTag categoriesFor: #type!accessing!public! !

