"Filed out from Dolphin Smalltalk 7"!

WAClosedRangeTag subclass: #WARangeInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WARangeInputTag guid: (GUID fromString: '{cf7cf078-c258-4e86-a216-8b817afccc57}')!
WARangeInputTag comment: 'supported on:- Safari 2.0 (slider)graceful degeneration to text inputFor this type, step defaults to 1, min defaults to 0, max defaults to 100, and value  defaults to the min value.Volume controls and brightness controls would be good examples of "range" data controls.'!
!WARangeInputTag categoriesForClass!Seaside-Canvas-Tags! !
!WARangeInputTag methodsFor!

type	^ 'range'! !
!WARangeInputTag categoriesFor: #type!accessing!public! !

