"Filed out from Dolphin Smalltalk"!

WAPresenterGuide subclass: #WARenderingGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARenderingGuide guid: (GUID fromString: '{b9ac8e1c-8d80-4939-ab0c-31609b72985c}')!

WARenderingGuide comment: 'Currently an empty class but still present for clarity and to allow customization of Rendering behaviour.'!

!WARenderingGuide categoriesForClass!Visitors! !

