"Filed out from Dolphin Smalltalk 7"!

GROrderedMultiMapTest subclass: #WARequestFieldsTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WARequestFieldsTest guid: (GUID fromString: '{ebbd93d8-b71d-47a5-8ca0-1ee5755d01aa}')!
WARequestFieldsTest comment: ''!
!WARequestFieldsTest categoriesForClass!Seaside-Tests-Core-HTTP! !
!WARequestFieldsTest methodsFor!

collectionClass	^ WARequestFields! !
!WARequestFieldsTest categoriesFor: #collectionClass!configuration!public! !

