"Filed out from Dolphin Smalltalk"!

GROrderedMultiMapTest subclass: #WARequestFieldsTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestFieldsTest guid: (GUID fromString: '{23e08c77-605d-4e98-af04-5d6c4a0bf6c8}')!

WARequestFieldsTest comment: ''!

!WARequestFieldsTest categoriesForClass!HTTP! !

!WARequestFieldsTest methodsFor!

collectionClass	^ WARequestFields! !

!WARequestFieldsTest categoriesForMethods!
collectionClass!configuration!public! !
!

