"Filed out from Dolphin Smalltalk 7"!

GROrderedMultiMap2 subclass: #WARequestFields
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WARequestFields guid: (GUID fromString: '{ec997804-ac4d-42f7-9e10-bf1d406f7b6e}')!
WARequestFields comment: ''!
!WARequestFields categoriesForClass!Seaside-Core-HTTP! !
!WARequestFields methodsFor!

seasideRequestFields	^ self! !
!WARequestFields categoriesFor: #seasideRequestFields!converting!public! !

