"Filed out from Dolphin Smalltalk"!

WAError subclass: #WARequestContextNotFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestContextNotFound guid: (GUID fromString: '{b8e8a719-a869-449d-932f-4b968950c010}')!

WARequestContextNotFound comment: 'This exception is raised when trying to obtain the current request context when none is available.'!

!WARequestContextNotFound categoriesForClass!Seaside-Core-Exceptions! !

