"Filed out from Dolphin Smalltalk"!

WAPresenterGuide subclass: #WARenderingGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARenderingGuide guid: (GUID fromString: '{e742a56e-68b5-4e7e-a873-8821488f4a8d}')!

WARenderingGuide comment: 'Currently an empty class but still present for clarity and to allow customization of Rendering behaviour.'!

!WARenderingGuide categoriesForClass!Seaside-Component-Visitors! !

