"Filed out from Dolphin Smalltalk 7"!

WAPresenterGuide subclass: #WARenderingGuide
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WARenderingGuide guid: (GUID fromString: '{c2aa87db-059b-466e-95bf-8242fdcbfda0}')!
WARenderingGuide comment: 'Currently an empty class but still present for clarity and to allow customization of Rendering behaviour.'!
!WARenderingGuide categoriesForClass!Seaside-Component-Visitors! !
