"Filed out from Dolphin Smalltalk"!

GROrderedMultiMap2 subclass: #WARequestFields
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestFields guid: (GUID fromString: '{e5be6db3-358d-4597-892d-1731e15062a4}')!

WARequestFields comment: ''!

!WARequestFields categoriesForClass!HTTP! !

!WARequestFields methodsFor!

seasideRequestFields	^ self! !

!WARequestFields categoriesForMethods!
seasideRequestFields!converting!public! !
!

