"Filed out from Dolphin Smalltalk"!

WAError subclass: #WARequestContextNotFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestContextNotFound guid: (GUID fromString: '{7fecad8e-4102-48c4-b6fb-26208d08fc47}')!

WARequestContextNotFound comment: 'This exception is raised when trying to obtain the current request context when none is available.'!

!WARequestContextNotFound categoriesForClass!Exceptions! !

