"Filed out from Dolphin Smalltalk"!

WASystemConfiguration subclass: #WARestfulConfiguration
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARestfulConfiguration guid: (GUID fromString: '{be39fe2b-8983-48e4-9c71-a99e6e9dfcda}')!

WARestfulConfiguration comment: ''!

!WARestfulConfiguration categoriesForClass!Seaside-REST-Core-Handler! !

