"Filed out from Dolphin Smalltalk 7"!

WAError subclass: #WARequestContextNotFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WARequestContextNotFound guid: (GUID fromString: '{a7f082c0-3445-46aa-bf53-adc02b0561ae}')!
WARequestContextNotFound comment: 'WANotification subclass: #WAResponseNotification	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Seaside-Core-Exceptions'''!
!WARequestContextNotFound categoriesForClass!Seaside-Core-Exceptions! !
