"Filed out from Dolphin Smalltalk"!

GROrderedMultiMapTest subclass: #WARequestFieldsTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestFieldsTest guid: (GUID fromString: '{be3fa1df-afb8-4238-a54a-102770de2f8b}')!

WARequestFieldsTest comment: ''!

!WARequestFieldsTest categoriesForClass!Seaside-Tests-Core-HTTP! !

!WARequestFieldsTest methodsFor!

collectionClass	^ WARequestFields! !

!WARequestFieldsTest categoriesForMethods!
collectionClass!configuration!public! !
!

