"Filed out from Dolphin Smalltalk"!

GROrderedMultiMap2 subclass: #WARequestFields
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARequestFields guid: (GUID fromString: '{f5b18927-ddc5-48a7-a929-51540892b945}')!

WARequestFields comment: ''!

!WARequestFields categoriesForClass!Seaside-Core-HTTP! !

!WARequestFields methodsFor!

seasideRequestFields	^ self! !

!WARequestFields categoriesForMethods!
seasideRequestFields!converting!public! !
!

