"Filed out from Dolphin Smalltalk"!

Object subclass: #WARouteVictimMock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WARouteVictimMock guid: (GUID fromString: '{33ee0764-f554-4c5d-ac87-89e5a8709c6d}')!

WARouteVictimMock comment: ''!

!WARouteVictimMock categoriesForClass!Seaside-Tests-REST-Core! !

!WARouteVictimMock methodsFor!

first: anObject	^ Array with: anObject!

first: anFirstObject second: aSecondObject	^ Array with: anFirstObject with: aSecondObject!

first: anFirstObject second: aSecondObject third: aThirdObject	^ Array with: anFirstObject with: aSecondObject with: aThirdObject!

nothing	^ Array new! !

!WARouteVictimMock categoriesForMethods!
first:!accessing!public! !
first:second:!accessing!public! !
first:second:third:!accessing!public! !
nothing!accessing!public! !
!

