"Filed out from Dolphin Smalltalk 7"!

WAHandlerTrackingStrategy subclass: #WASessionTrackingStrategy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WASessionTrackingStrategy guid: (GUID fromString: '{4f283b0e-ab57-45f4-b321-91398a487411}')!
WASessionTrackingStrategy comment: 'WASessionTrackingStrategy class	instanceVariableNames: '''''!
!WASessionTrackingStrategy categoriesForClass!Seaside-Session! !
!WASessionTrackingStrategy class methodsFor!

isAbstract	^ self name = #WASessionTrackingStrategy! !
!WASessionTrackingStrategy class categoriesFor: #isAbstract!public!testing! !

