"Filed out from Dolphin Smalltalk 7"!

WAErrorHandler subclass: #WASignalingErrorHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WASignalingErrorHandler guid: (GUID fromString: '{91c3e02d-7ab2-4499-9233-d06f9720aea9}')!
WASignalingErrorHandler comment: ''!
!WASignalingErrorHandler categoriesForClass!Seaside-Tests-RenderLoop! !
!WASignalingErrorHandler methodsFor!

handleException: anException	WARenderNotification signal! !
!WASignalingErrorHandler categoriesFor: #handleException:!actions!public! !

