"Filed out from Dolphin Smalltalk 7"!

WAErrorHandler subclass: #WASignalingErrorHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WASignalingErrorHandler guid: (GUID fromString: '{09a5c95a-2a3a-435a-9c8e-e817c41a041e}')!
WASignalingErrorHandler comment: ''!
!WASignalingErrorHandler categoriesForClass!Seaside-Tests-RenderLoop! !
!WASignalingErrorHandler methodsFor!

handleException: anException	WARenderNotification signal! !
!WASignalingErrorHandler categoriesFor: #handleException:!actions!public! !

