"Filed out from Dolphin Smalltalk"!

WAErrorHandler subclass: #WASignalingErrorHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WASignalingErrorHandler guid: (GUID fromString: '{e2841226-4ca0-49fa-8b41-06f202635c3f}')!

WASignalingErrorHandler comment: ''!

!WASignalingErrorHandler categoriesForClass!Seaside-Tests-RenderLoop! !

!WASignalingErrorHandler methodsFor!

handleException: anException	WARenderNotification signal! !

!WASignalingErrorHandler categoriesForMethods!
handleException:!actions!public! !
!

