"Filed out from Dolphin Smalltalk 7"!

WAAbstractTextAreaTag subclass: #WASteppedTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WASteppedTag guid: (GUID fromString: '{b6b1b161-6761-48f4-bdab-2bf3421ade9a}')!
WASteppedTag comment: 'Common superclass for step related tags'!
!WASteppedTag categoriesForClass!Seaside-Canvas-Tags! !
!WASteppedTag methodsFor!

step: anInteger	self attributeAt: 'step' put: anInteger! !
!WASteppedTag categoriesFor: #step:!attributes!public! !

