"Filed out from Dolphin Smalltalk"!

WAFunctionalTest subclass: #WASvgFunctionalTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WASvgFunctionalTest guid: (GUID fromString: '{3bfcd056-f98d-4940-9ce3-891bc7ddc706}')!

WASvgFunctionalTest comment: ''!

!WASvgFunctionalTest categoriesForClass!Unclassified! !

!WASvgFunctionalTest methodsFor!

renderContentOn: html	html object		type: 'image/svg+xml' seasideMimeType;		width: 512;		height: 512;		standby: 'loading tiger';		url: 'http://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg';		with: 'Your browser doesn''t support SVG'! !

!WASvgFunctionalTest categoriesForMethods!
renderContentOn:!public!rendering! !
!

