"Filed out from Dolphin Smalltalk 7"!

WATableColumnGroupTag subclass: #WATableColumnTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATableColumnTag guid: (GUID fromString: '{cd0741a2-cb30-4421-b755-3083db1e6d7d}')!
WATableColumnTag comment: 'WATableColumnTag elements define the alignment properties for cells in one or more columns.'!
!WATableColumnTag categoriesForClass!Seaside-Canvas-Tags! !
!WATableColumnTag methodsFor!

isClosed	^ true!

tag	^ 'col'! !
!WATableColumnTag categoriesFor: #isClosed!public!testing! !
!WATableColumnTag categoriesFor: #tag!accessing!public! !

