"Filed out from Dolphin Smalltalk 7"!

WATableColumnGroupTag subclass: #WATableColumnTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATableColumnTag guid: (GUID fromString: '{c4b6a0e4-1cb9-4e51-846b-decf132987d7}')!
WATableColumnTag comment: 'WATableColumnTag elements define the alignment properties for cells in one or more columns.'!
!WATableColumnTag categoriesForClass!Seaside-Canvas-Tags! !
!WATableColumnTag methodsFor!

isClosed	^ true!

tag	^ 'col'! !
!WATableColumnTag categoriesFor: #isClosed!public!testing! !
!WATableColumnTag categoriesFor: #tag!accessing!public! !

