"Filed out from Dolphin Smalltalk"!

WATableColumnGroupTag subclass: #WATableColumnTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATableColumnTag guid: (GUID fromString: '{706c9836-301c-4310-82a8-a9bbfa1bc542}')!

WATableColumnTag comment: 'WATableColumnTag elements define the alignment properties for cells in one or more columns.'!

!WATableColumnTag categoriesForClass!Tags! !

!WATableColumnTag methodsFor!

isClosed	^ true!

tag	^ 'col'! !

!WATableColumnTag categoriesForMethods!
isClosed!public!testing! !
tag!accessing!public! !
!

