"Filed out from Dolphin Smalltalk 7"!

WATableDataTag subclass: #WATableHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATableHeadingTag guid: (GUID fromString: '{5dbb8f57-ad3d-4e77-bdd1-05baf8b261c9}')!
WATableHeadingTag comment: 'The WATableHeadingTag defines a table header cell in a table. The text within the th element usually renders in bold.'!
!WATableHeadingTag categoriesForClass!Seaside-Canvas-Tags! !
!WATableHeadingTag methodsFor!

tag	^ 'th'! !
!WATableHeadingTag categoriesFor: #tag!accessing!public! !

