"Filed out from Dolphin Smalltalk 7"!

WATableDataTag subclass: #WATableHeadingTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATableHeadingTag guid: (GUID fromString: '{7e4f3b49-97c9-4a6b-9516-db168e775b95}')!
WATableHeadingTag comment: 'The WATableHeadingTag defines a table header cell in a table. The text within the th element usually renders in bold.'!
!WATableHeadingTag categoriesForClass!Seaside-Canvas-Tags! !
!WATableHeadingTag methodsFor!

tag	^ 'th'! !
!WATableHeadingTag categoriesFor: #tag!accessing!public! !

