"Filed out from Dolphin Smalltalk"!

WAServerManager subclass: #WATestServerManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATestServerManager guid: (GUID fromString: '{f6537d9b-981c-4cd1-8e7c-fe2645963d6a}')!

WATestServerManager comment: 'I am a server manager used as an alternative of the WAServerManager, because some Smalltalk dialects have subclasses of WAServerManager.'!

!WATestServerManager categoriesForClass!Seaside-Tests-Core-Server! !

