"Filed out from Dolphin Smalltalk"!

WASession subclass: #WATestSession
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATestSession guid: (GUID fromString: '{b3f1cb5e-bbe5-4854-b5ab-b94fbc6ee149}')!

WATestSession comment: ''!

!WATestSession categoriesForClass!Seaside-Tests-Session! !

!WATestSession methodsFor!

start	(self requestContext response)		nextPutAll: 'start: ';		nextPutAll: self key! !

!WATestSession categoriesForMethods!
start!handling!public! !
!

