"Filed out from Dolphin Smalltalk"!

WAAbstractTextAreaTag subclass: #WATelephoneInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATelephoneInputTag guid: (GUID fromString: '{93951ea4-945b-4b13-86e0-5cab596e1e9a}')!

WATelephoneInputTag comment: 'Used to let the user enter and edit a telephone number'!

!WATelephoneInputTag categoriesForClass!Seaside-Canvas-Tags! !

!WATelephoneInputTag methodsFor!

type	^ 'tel'! !

!WATelephoneInputTag categoriesForMethods!
type!accessing!public! !
!

