"Filed out from Dolphin Smalltalk 7"!

WAAbstractTextAreaTag subclass: #WATelephoneInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATelephoneInputTag guid: (GUID fromString: '{9789680b-f818-4611-b7e2-b9dd58beb6c7}')!
WATelephoneInputTag comment: ''!
!WATelephoneInputTag categoriesForClass!Seaside-Canvas-Tags! !
!WATelephoneInputTag methodsFor!

type	^ 'tel'! !
!WATelephoneInputTag categoriesFor: #type!accessing!public! !

