"Filed out from Dolphin Smalltalk"!

WAFileHandlerListingTest subclass: #WATextFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATextFileHandlerListingTest guid: (GUID fromString: '{bf486db4-f9fb-42f1-be1c-6e1549e3259d}')!

WATextFileHandlerListingTest comment: ''!

!WATextFileHandlerListingTest categoriesForClass!Libraries! !

!WATextFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textPlain!

handlerClass	^ WATextFileHandlerListing! !

!WATextFileHandlerListingTest categoriesForMethods!
expectedMimeType!public!testing! !
handlerClass!public!testing! !
!

