"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #WATestError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestError guid: (GUID fromString: '{9976cf95-0973-4907-b634-36c7d278b9d3}')!
WATestError comment: 'TestCase subclass: #WARenderContextTest	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Seaside-Tests-Core-Rendering'''!
!WATestError categoriesForClass!Seaside-Tests-Core-Base! !
