"Filed out from Dolphin Smalltalk"!

WARequestHandler subclass: #WATestNoopRequestHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATestNoopRequestHandler guid: (GUID fromString: '{a1b20ebf-3cfe-48bd-92b9-fc16e9da8d30}')!

WATestNoopRequestHandler comment: ''!

!WATestNoopRequestHandler categoriesForClass!Seaside-Tests-Core-RequestHandling! !

!WATestNoopRequestHandler methodsFor!

handleFiltered: aRequestContext	"do nothing"! !

!WATestNoopRequestHandler categoriesForMethods!
handleFiltered:!handling!public! !
!

