"Filed out from Dolphin Smalltalk 7"!

WAFileHandlerListingTest subclass: #WATextFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATextFileHandlerListingTest guid: (GUID fromString: '{ea000df2-fcaa-4857-a168-9d1ad1912b73}')!
WATextFileHandlerListingTest comment: ''!
!WATextFileHandlerListingTest categoriesForClass!Seaside-Tests-Core-Libraries! !
!WATextFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textPlain!

handlerClass	^ WATextFileHandlerListing! !
!WATextFileHandlerListingTest categoriesFor: #expectedMimeType!public!testing! !
!WATextFileHandlerListingTest categoriesFor: #handlerClass!public!testing! !

