"Filed out from Dolphin Smalltalk"!

WAServerManager subclass: #WATestServerManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATestServerManager guid: (GUID fromString: '{b7887c6c-e54c-459c-bfa4-309b4124d3fd}')!

WATestServerManager comment: 'I am a server manager used as an alternative of the WAServerManager, because some Smalltalk dialects have subclasses of WAServerManager.'!

!WATestServerManager categoriesForClass!Server! !

