"Filed out from Dolphin Smalltalk"!

WASession subclass: #WATestSession
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATestSession guid: (GUID fromString: '{a5a850a7-4f6a-4cd2-b94c-db5067979880}')!

WATestSession comment: ''!

!WATestSession categoriesForClass!Unclassified! !

!WATestSession methodsFor!

start	(self requestContext response)		nextPutAll: 'start: ';		nextPutAll: self key! !

!WATestSession categoriesForMethods!
start!handling!public! !
!

