"Filed out from Dolphin Smalltalk 7"!

WARequestHandler subclass: #WATestNoopRequestHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestNoopRequestHandler guid: (GUID fromString: '{449ea4b4-087d-47f2-83af-4febfb2df3dc}')!
WATestNoopRequestHandler comment: ''!
!WATestNoopRequestHandler categoriesForClass!Seaside-Tests-Core-RequestHandling! !
!WATestNoopRequestHandler methodsFor!

handleFiltered: aRequestContext	"do nothing"! !
!WATestNoopRequestHandler categoriesFor: #handleFiltered:!handling!public! !

