"Filed out from Dolphin Smalltalk"!

WAAbstractTextAreaTag subclass: #WATelephoneInputTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WATelephoneInputTag guid: (GUID fromString: '{2b377293-ee51-4c00-8731-b60cdd8d553b}')!

WATelephoneInputTag comment: 'Used to let the user enter and edit a telephone number'!

!WATelephoneInputTag categoriesForClass!Tags! !

!WATelephoneInputTag methodsFor!

type	^ 'tel'! !

!WATelephoneInputTag categoriesForMethods!
type!accessing!public! !
!

