"Filed out from Dolphin Smalltalk 7"!

WAFileHandlerListingTest subclass: #WATextFileHandlerListingTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATextFileHandlerListingTest guid: (GUID fromString: '{fe6b3393-7a82-43f5-9af1-356d244dd1ba}')!
WATextFileHandlerListingTest comment: ''!
!WATextFileHandlerListingTest categoriesForClass!Seaside-Tests-Core-Libraries! !
!WATextFileHandlerListingTest methodsFor!

expectedMimeType	^ WAMimeType textPlain!

handlerClass	^ WATextFileHandlerListing! !
!WATextFileHandlerListingTest categoriesFor: #expectedMimeType!public!testing! !
!WATextFileHandlerListingTest categoriesFor: #handlerClass!public!testing! !

