"Filed out from Dolphin Smalltalk 7"!

WARequestHandler subclass: #WATestNoopRequestHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WATestNoopRequestHandler guid: (GUID fromString: '{5b8a63b0-a26e-4ee1-979d-28b727a9cc4f}')!
WATestNoopRequestHandler comment: ''!
!WATestNoopRequestHandler categoriesForClass!Seaside-Tests-Core-RequestHandling! !
!WATestNoopRequestHandler methodsFor!

handleFiltered: aRequestContext	"do nothing"! !
!WATestNoopRequestHandler categoriesFor: #handleFiltered:!handling!public! !

