"Filed out from Dolphin Smalltalk"!

WAListTag subclass: #WAUnorderedListTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAUnorderedListTag guid: (GUID fromString: '{b5565914-94e8-4a9e-ab1b-abed58379517}')!

WAUnorderedListTag comment: 'See superclass comment.'!

!WAUnorderedListTag categoriesForClass!Seaside-Canvas-Tags! !

!WAUnorderedListTag methodsFor!

tag	^ 'ul'! !

!WAUnorderedListTag categoriesForMethods!
tag!accessing!public! !
!

