"Filed out from Dolphin Smalltalk 7"!

WAListTag subclass: #WAUnorderedListTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAUnorderedListTag guid: (GUID fromString: '{e26cff37-24ef-4f97-ab1b-f169508e695c}')!
WAUnorderedListTag comment: 'See superclass comment.'!
!WAUnorderedListTag categoriesForClass!Seaside-Canvas-Tags! !
!WAUnorderedListTag methodsFor!

tag	^ 'ul'! !
!WAUnorderedListTag categoriesFor: #tag!accessing!public! !

