"Filed out from Dolphin Smalltalk 7"!

WAListTag subclass: #WAUnorderedListTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAUnorderedListTag guid: (GUID fromString: '{96b9d685-6599-48bd-9695-f8333bdf2247}')!
WAUnorderedListTag comment: 'See superclass comment.'!
!WAUnorderedListTag categoriesForClass!Seaside-Canvas-Tags! !
!WAUnorderedListTag methodsFor!

tag	^ 'ul'! !
!WAUnorderedListTag categoriesFor: #tag!accessing!public! !

