"Filed out from Dolphin Smalltalk 7"!

WANotification subclass: #WAValidationNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WAValidationNotification guid: (GUID fromString: '{d42884b1-c3d7-4a1f-8329-eaba166733df}')!
WAValidationNotification comment: 'WADecoration subclass: #WAWidgetDecoration	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Seaside-Widgets-Decorations'''!
!WAValidationNotification categoriesForClass!Seaside-Widgets-Decorations! !
