"Filed out from Dolphin Smalltalk"!

WAAttributeExpression subclass: #WAValueExpression
	instanceVariableNames: 'value'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAValueExpression guid: (GUID fromString: '{965fcbee-856d-4e36-b3b2-65651074a352}')!

WAValueExpression comment: ''!

!WAValueExpression categoriesForClass!Seaside-Core-Configuration! !

!WAValueExpression methodsFor!

determineValueWithContext: aContext configuration: aConfiguration	^ self value!

value	^ value!

value: anObject	value := anObject! !

!WAValueExpression categoriesForMethods!
determineValueWithContext:configuration:!public!values! !
value!accessing!public! !
value:!accessing!public! !
!

