"Filed out from Dolphin Smalltalk"!

WANotification subclass: #WAValidationNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAValidationNotification guid: (GUID fromString: '{81b79197-204d-411c-a8e5-989844351950}')!

WAValidationNotification comment: 'I am signaled to indicate that a validation has occurred.  See: WAFormDialog>>#validationError:, WAComponent>>validateWith: and WAValidationDecoration.'!

!WAValidationNotification categoriesForClass!Seaside-Widgets-Decorations! !

