"Filed out from Dolphin Smalltalk"!

WANotification subclass: #WAValidationNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WAValidationNotification guid: (GUID fromString: '{b7b6582b-c183-4e6d-b311-2140d0f487d9}')!

WAValidationNotification comment: 'I am signaled to indicate that a validation has occurred.  See: WAFormDialog>>#validationError:, WAComponent>>validateWith: and WAValidationDecoration.'!

!WAValidationNotification categoriesForClass!Decorations! !

