"Filed out from Dolphin Smalltalk"!

Object subclass: #WebBrowser
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

WebBrowser guid: (GUID fromString: '{a7930061-fb75-4616-b304-15efd4353344}')!

WebBrowser comment: ''!

!WebBrowser categoriesForClass!Kernel-Objects! !

!WebBrowser class methodsFor!

openOn: aString

	^ShellLibrary default shellOpen: aString! !

!WebBrowser class categoriesForMethods!
openOn:!public! !
!

