"Filed out from Dolphin Smalltalk 7"!

WorkingHTTPSetCookieField subclass: #WorkingHTTPSetCookie2Field
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WorkingHTTPSetCookie2Field guid: (GUID fromString: '{04a48576-223c-426b-8d04-2c5a2a0f7aa8}')!
WorkingHTTPSetCookie2Field comment: '
A WorkingHTTPSetCookie2Field is a Set-Cookie2 header field, currently only suported by Opera.
'!
!WorkingHTTPSetCookie2Field categoriesForClass!Unclassified! !
!WorkingHTTPSetCookie2Field class methodsFor!

fieldName
	^'Set-Cookie2'! !
!WorkingHTTPSetCookie2Field class categoriesFor: #fieldName!accessing!public! !

